<?php
/**
 * Designer list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
/* @var $this Validoc_Designer_Block_List */
?>
<?php
    $byWhat = 'attributes';
    //values can be between "attributes" for list by attributes or "fabrics" for list directly by fabrics
    if($byWhat == 'attributes'){
        //for print by magento attributes
        $collectionType = Mage::registry('fabricType');
        $fabricsCollection = $this->getFabricAttributtes($collectionType);
        $type_id = Mage::registry('type_id');
        $_fabricCollection = $this->getLoadedFabricCollection();
    }else{
        $_fabricCollection = $this->getLoadedFabricCollection();
    }

$_helper = $this->helper('catalog/output');
//print_r($_fabricCollection);
?>
<?php if(!$_fabricCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no items matching the selection.') ?></p>
<?php else: ?>
    <div class="category-products fabrics-list">
        <?php //echo $this->getToolbarHtml() ?>
        <div class="page-title category-title">
            <?php
                if(Mage::registry('fabricType') == 'all'){
                    $fabricType = '';
                    $preText = '';
                }else if(Mage::registry('fabricType') == 'source'){
                    $fabricType = 'source';
                    $preText = 'by';
                }else{
                    $fabricType = 'color';
                    $preText = 'by';
                }
            ?>
            <h1>
                <span class="title_1"><?php echo __('Fabrics')?> <span style="text-transform: none;"><?php echo $preText; ?></span> <span><?php echo $fabricType; ?></span></span>
                <?php
                    if(isset($type_id)):
                        if(Mage::registry('fabricType') == 'source'){
                            $attributeModel = Mage::getModel('eav/config')->getAttribute('catalog_product', 'manufacturer');
                        }else if(Mage::registry('fabricType') == 'color'){
                            $attributeModel = Mage::getModel('eav/config')->getAttribute('catalog_product', 'color');
                        }

                        $allOptions = $attributeModel->getSource()->getAllOptions(true, true);
                        foreach ($allOptions as $instance) {
                            if($instance['value'] == $type_id){
                                $title_2 = $instance['label'];
                            }
                        }
                ?>
                    <span class="title_2">| <?php echo $title_2; ?></span>
                <?php endif; ?>
            </h1>
        </div>
        <?php //echo $this->getChildHtml('fabric_list_toolbar_custom'); ?>
        <?php // List mode ?>
        <?php if($this->getMode()!='grid'): ?>
            <?php $_iterator = 0; ?>
            <ol class="products-list" id="products-list">
                <?php foreach ($_fabricCollection as $_fabric): ?>
                    <?php $_fabric->load($_fabric->getId()); ?>
                    <li class="item<?php if( ++$_iterator == sizeof($_fabricCollection) ): ?> last<?php endif; ?>">
                        <?php // Product Image ?>
                        <a href="<?php echo Mage::getUrl("*/*/view",array("id"=>$_fabric->getId())); ?>" title="<?php echo $this->stripTags($this->getImageLabel($_fabric, 'small_image'), null, true) ?>" class="product-image">
                            <?php /* Based on the native RWD styling, product images are displayed at a max of ~400px wide when viewed on a
                        one column page layout with four product columns from a 1280px viewport. For bandwidth reasons,
                        we are going to serve a 300px image, as it will look fine at 400px and most of the times, the image
                        will be displayed at a smaller size (eg, if two column are being used or viewport is smaller than 1280px).
                        This $_imgSize value could even be decreased further, based on the page layout
                        (one column, two column, three column) and number of product columns. */ ?>
                            <?php $_imgSize = 300; ?>
                            <img id="product-collection-image-<?php echo $_fabric->getId(); ?>"
                                 src="<?php echo $this->helper('validoc_fabric/image')->init($_fabric, 'small_image')->resize($_imgSize); ?>"
                                 alt="<?php //echo $this->stripTags($this->getImageLabel($_designer, 'small_image'), null, true) ?>" />
                        </a>
                        <?php // Product description ?>
                        <div class="product-shop">
                            <div class="f-fix">
                                <div class="product-primary">
                                    <?php $_fabricNameStripped = $this->stripTags($_fabric->getName(), null, true); ?>
                                    <h2 class="product-name"><a href="<?php echo Mage::getUrl("*/*/view",array("id"=>$_fabric->getId())); ?>" title="<?php echo $_fabricNameStripped; ?>"><?php echo $_fabric->getName(); ?></a></h2>

                                    <?php
                                    $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
                                    foreach($_nameAfterChildren as $_nameAfterChildName):
                                        $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
                                        $_nameAfterChild->setProduct($_fabric);
                                        ?>
                                        <?php echo $_nameAfterChild->toHtml(); ?>
                                    <?php endforeach; ?>
                                </div>

                                <div class="desc std">
                                    <?php echo $_fabric->getDescription(); ?>
                                    <a href="<?php echo Mage::getUrl("*/*/view",array("id"=>$_fabric->getId())); ?>" title="<?php echo $_fabricNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                                </div>
                            </div>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ol>
            <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

        <?php else: ?>

        <?php // Grid Mode ?>

        <?php $_collectionSize = $_fabricCollection->count() ?>
        <?php $_columnCount = $this->getColumnCount(); ?>
            <!-- <div class="manufacturer-name">
                <h2><?php //echo $this->__('Manufacturer Name'); ?></h2>
            </div> -->
            <?php if($byWhat == 'fabrics'): ?>
            <ul class="products-grid products-grid--max-<?php echo $_columnCount; ?>-col">
                <?php $i=0; foreach ($_fabricCollection as $_fabric): ?>
                    <?php //echo '<pre>'.print_r($_fabric, true).'</pre>'; ?>
                    <?php $_fabric->load($_fabric->getId()); ?>
                    <?php /*if ($i++%$_columnCount==0): ?>
            <?php endif*/ ?>

                    <!--<li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">-->
                    <li class="grid12-3">

                        <a href="<?php echo Mage::getUrl("*/*/view",array("id"=>$_fabric->getId())); ?>" title="<?php //echo $this->stripTags($this->getImageLabel($_designer, 'small_image'), null, true) ?>" class="product-image">
                            <?php $_imgSize = 324; ?>
                            <img id="product-collection-image-<?php echo $_fabric->getId(); ?>"
                                 src="<?php echo $this->helper('validoc_fabric/image')->init($_fabric, 'small_image')->resize($_imgSize); ?>"
                                 alt="<?php //echo $this->stripTags($this->getImageLabel($_designer, 'small_image'), null, true) ?>" />
                        </a>
                        <div class="product-info">
                            <!--<h2 class="product-name"><a href="<?php echo Mage::getUrl("*/*/view",array("id"=>$_fabric->getId())); ?>" title="<?php //echo $this->stripTags($_designer->getName(), null, true) ?>"><?php echo $_fabric->getName(); ?></a></h2>
                            <h2 class="product-name"><a href="<?php echo Mage::getUrl("*/*/view",array("id"=>$_fabric->getId())); ?>" title="<?php //echo $this->stripTags($_designer->getName(), null, true) ?>"><?php echo $_fabric->getManufacturer(); ?></a></h2>-->
                            <p>
                                <a href="<?php echo Mage::getUrl("*/*/view",array("id"=>$_fabric->getId())); ?>" title="<?php //echo $this->stripTags($_designer->getName(), null, true) ?>"><?php echo $_fabric->getName(); ?></a>
                            </p>
                            <?php
                            $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
                            foreach($_nameAfterChildren as $_nameAfterChildName):
                                $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
                                $_nameAfterChild->setProduct($_fabric);
                                ?>
                                <?php echo $_nameAfterChild->toHtml(); ?>
                            <?php endforeach; ?>
                        </div>
                    </li>
                    <?php /*if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
            <?php endif*/ ?>
                <?php endforeach ?>
            </ul><!-- products-grid -->


            <?php else://attributes ?>
                <?php if(!isset($type_id)): ?>
                <ul class="products-grid products-grid--max-<?php echo $_columnCount; ?>-col">
                    <?php foreach($fabricsCollection as $key => $fabric): ?>
                        <?php if(!empty($key)): ?>
                            <li class="grid12-3">
                                <a href="<?php echo Mage::getUrl("*/*/list", array('type' => Mage::registry('fabricType'), 'type_id' => $key)); ?>" title="<?php echo $fabric; ?>">
                                    <img id="product-collection-image-<?php echo $key; ?>"
                                         src="<?php echo Mage::helper('attributeoptionimage')->getAttributeOptionImage($key); ?>"
                                         alt="<?php $fabric; ?>" />
                                </a>
                                <div class="product-info">
                                    <p><a href="<?php echo Mage::getUrl("*/*/list", array('type' => Mage::registry('fabricType'), 'type_id' => $key)); ?>"><?php echo $fabric; ?></a></p>
                                </div>
                            </li>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </ul>
                <?php else: ?>
                    <ul class="products-grid products-grid--max-<?php echo $_columnCount; ?>-col">
                        <?php foreach($_fabricCollection as $_fabric): ?>
                            <?php $_fabric->load($_fabric->getId()); ?>
                            <?php //var_dump($_fabric); ?>
                            <li class="grid12-3">
                                <a href="<?php echo $_fabric->getId(); ?>" class="product-image">
                                    <?php $_imgSize = 324; ?>
                                    <img id="product-collection-image-<?php echo $_fabric->getId(); ?>"
                                         src="<?php echo $this->helper('validoc_fabric/image')->init($_fabric, 'small_image')->resize($_imgSize); ?>" />
                                </a>
                                <div class="product-info">
                                    <p><a href="<?php echo $_fabric->getId(); ?>"><?php echo $_fabric->getName(); ?></a></p>
                                </div>
                            </li>
                            <div class="container popup" id="<?php echo $_fabric->getId(); ?>" style="display: none;">
                                <div class="grid12-6 popup-images">
                                    <div class="main-img">
                                        <img src="<?php echo $this->helper('validoc_fabric/image')->init($_fabric, 'small_image')->resize($_imgSize); ?>">
                                    </div>
                                    <div class="extra-imgs">
                                        <ul>
                                            <?php $fabricExtraImg = $_fabric->getMediaGallery(); ?>
                                            <?php foreach($fabricExtraImg['images'] as $img): ?>
                                                <li>
                                                    <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>validoc/fabric<?php echo $img['file']; ?>">
                                                </li>
                                            <?php endforeach; ?>
                                        </ul>
                                    </div>
                                </div>
                                <div class="grid12-6 popup-info">
                                    <h2><?php echo $title_2; ?></h2>
                                    <?php
                                        $rooms = $_fabric->getRoom();
                                        if(!empty($rooms)){
                                            $roomIds = explode(",",$rooms);
                                            $boardsCollection = array();
                                            foreach ($roomIds as $key => $roomId) {
                                                $board = Mage::getModel('validoc_board/board')->load($roomId);
                                                array_push($boardsCollection, $board);
                                            }
                                        }
                                    ?>
                                    <p>featured in <span><?php
                                    if(!empty($boardsCollection)):
                                    foreach ($boardsCollection as $key => $board) {
                                        echo '<a href="'.Mage::getBaseUrl().'designer-board/board/view/id/'.$board->getBoardId().'">'.$board->getName();
                                        if($key != count($boardsCollection)-1){
                                            echo "</a>, ";
                                        }else{
                                            echo "</a>";
                                        }
                                    }
                                    endif;
                                    ?></span></p>
                                    <p class="description"><?php echo $_fabric->getDescription(); ?></p>
                                    <a href="#" class="shop" style="display: none;">shop this room</a>
                                </div>
                            </div>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
            <?php endif; ?>
            <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
        <?php endif; ?>

        <!--<div class="toolbar-bottom">
            <?php //echo $this->getToolbarHtml() ?>
        </div>-->
    </div>
<?php endif; ?>

<div class="clearer"></div>

<!-- <div class="box-header-design">
    <span class="box-header-title">
        <img src="<?php echo $this->getSkinUrl('images/media/design-logo.png') ?>" alt="" />
    </span>
</div> -->

<?php
//set product collection on after blocks
$_afterChildren = $this->getChild('after')->getSortedChildren();
foreach($_afterChildren as $_afterChildName):
    $_afterChild = $this->getChild('after')->getChild($_afterChildName);
    $_afterChild->setProductCollection($_fabricCollection);
    ?>
    <?php echo $_afterChild->toHtml(); ?>
<?php endforeach; ?>

<script type="text/javascript">
    var Handler = {
        onReady: function(){
            Handler.popup();
            Handler.changeImgs();
            Handler.equalizeHeights();
        },
        popup: function(){
            jQuery('.product-image, .product-info p a').on('click', function(){
                var target = jQuery(this).attr('href');
                jQuery('.logo.logo--regular, #nav, .footer-container').css('z-index', '9');
                jQuery('.product-image, .product-info p a').fancybox({
                    href: '#' + target,
                    titleShow: false,
                    transitionIn: 'elastic',
                    transitionOut: 'elastic',
                    autoscale : true,
                    scrolling : 'no',
                    maxWidth : 800,
                    maxHeight: 550,
                    width: '100%',
                    height: 550,
                    autoSize: false,
                    afterClose: function(){
                        jQuery('.logo.logo--regular, #nav, .footer-container, .sticky-container, .footer-container').removeAttr('style');
                    },
                    beforeShow: function(){
                        jQuery('#nav, .sticky-container, .footer-container').css('z-index', '5');
                        jQuery('.logo.logo--regular').css('z-index', '6');
                    }
                });
            });
        },
        changeImgs: function(){
            var mainImg = jQuery('.main-img img');
            jQuery('.extra-imgs ul li img').click(function(){
                mainImg.attr('src', jQuery(this).attr('src'));
            });
        },
        equalizeHeights: function(){
            var firstBlock = jQuery('.popup-images').height();
            jQuery('.popup-info').css('height', firstBlock);
        }
    };
    jQuery(document).on('ready', Handler.onReady());
</script>