<?php
/**
 * Designer board list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
/* @var $this Mage_Catalog_Block_Product_List */
?>
<?php
$_boardCollection=$this->_prepareLayout();
$_helper = $this->helper('catalog/output');
?>
<?php if(!$_boardCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no boards matching the selection.') ?></p>
<?php else: ?>
    <div class="category-products">
        <?php echo $this->getToolbarHtml() ?>
        <?php // List mode ?>
        <?php if($this->getMode()!='grid'): ?>
            <?php $_iterator = 0; ?>
            <ol class="products-list" id="products-list">
                <?php foreach ($_boardCollection as $_board): ?>
                    <li class="item<?php if( ++$_iterator == sizeof($_boardCollection) ): ?> last<?php endif; ?>">
                        <?php // Product Image ?>
                        <a href="<?php echo Mage::getUrl("*/detail",array("id"=>$_board->getId())); ?>" title="<?php echo $this->stripTags($this->getImageLabel($_board, 'small_image'), null, true) ?>" class="product-image">
                            <?php /* Based on the native RWD styling, product images are displayed at a max of ~400px wide when viewed on a
                        one column page layout with four product columns from a 1280px viewport. For bandwidth reasons,
                        we are going to serve a 300px image, as it will look fine at 400px and most of the times, the image
                        will be displayed at a smaller size (eg, if two column are being used or viewport is smaller than 1280px).
                        This $_imgSize value could even be decreased further, based on the page layout
                        (one column, two column, three column) and number of product columns. */ ?>
                            <?php $_imgSize = 300; ?>
                            <img id="product-collection-image-<?php echo $_board->getId(); ?>"
                                 src="<?php echo $this->helper('validoc_atp/imageboard')->init($_board, 'small_image')->keepFrame(false)->resize($_imgSize); ?>"
                                 alt="<?php //echo $this->stripTags($this->getImageLabel($_board, 'small_image'), null, true) ?>" />
                        </a>
                        <?php // Product description ?>
                        <div class="product-shop">
                            <div class="f-fix">
                                <div class="product-primary">
                                    <?php $_boardNameStripped = $this->stripTags($_board->getName(), null, true); ?>
                                    <h2 class="product-name"><a href="<?php echo Mage::getUrl("*/detail",array("id"=>$_board->getId())); ?>" title="<?php echo $_boardNameStripped; ?>"><?php echo $_board->getName(); ?></a></h2>

                                    <?php
                                    $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
                                    foreach($_nameAfterChildren as $_nameAfterChildName):
                                        $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
                                        $_nameAfterChild->setProduct($_board);
                                        ?>
                                        <?php echo $_nameAfterChild->toHtml(); ?>
                                    <?php endforeach; ?>
                                </div>

                                <div class="desc std">
                                    <?php echo $_board->getDescription(); ?>
                                    <a href="<?php echo Mage::getUrl("*/detail",array("id"=>$_board->getId())); ?>" title="<?php echo $_boardNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                                </div>
                            </div>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ol>
            <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

        <?php else: ?>

        <?php // Grid Mode ?>

        <?php $_collectionSize = $_boardCollection->count() ?>
        <?php $_columnCount = $this->getColumnCount(); ?>
            <ul class="products-grid products-grid--max-<?php echo $_columnCount; ?>-col">
                <?php $i=0; foreach ($_boardCollection as $_board): ?>
                    <?php $_board->load($_board->getId()); ?>
                    <?php /*if ($i++%$_columnCount==0): ?>
            <?php endif*/ ?>

                    <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">

                        <a href="<?php echo Mage::getUrl("*/detail",array("id"=>$_board->getId())); ?>" title="<?php //echo $this->stripTags($this->getImageLabel($_board, 'small_image'), null, true) ?>" class="product-image">
                            <?php $_imgSize = 210; ?>
                            <img id="product-collection-image-<?php echo $_board->getId(); ?>"
                                 src="<?php echo $this->helper('validoc_atp/imageboard')->init($_board, 'small_image')->resize($_imgSize); ?>"
                                 alt="<?php //echo $this->stripTags($this->getImageLabel($_board, 'small_image'), null, true) ?>" />
                        </a>
                        <?php echo "dfasdfsdf"; ?>
                        <div class="product-info">
                            <h2 class="product-name"><a href="<?php echo Mage::getUrl("*/detail",array("id"=>$_board->getId())); ?>" title="<?php //echo $this->stripTags($_board->getName(), null, true) ?>"><?php echo $_board->getName(); ?></a></h2>

                            <?php
                            $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
                            foreach($_nameAfterChildren as $_nameAfterChildName):
                                $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
                                $_nameAfterChild->setProduct($_board);
                                ?>
                                <?php echo $_nameAfterChild->toHtml(); ?>
                            <?php endforeach; ?>
                        </div>
                    </li>
                    <?php /*if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
            <?php endif*/ ?>
                <?php endforeach ?>
            </ul>
            <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
        <?php endif; ?>

        <div class="toolbar-bottom">
            <?php echo $this->getToolbarHtml() ?>
        </div>
    </div>
<?php endif; ?>

<?php
//set product collection on after blocks
$_afterChildren = $this->getChild('after')->getSortedChildren();
foreach($_afterChildren as $_afterChildName):
    $_afterChild = $this->getChild('after')->getChild($_afterChildName);
    $_afterChild->setProductCollection($_boardCollection);
    ?>
    <?php echo $_afterChild->toHtml(); ?>
<?php endforeach; ?>
