<?php
/**
 * Created by PhpStorm.
 * User: Juan Carlos
 * Date: 5/7/2015
 * Time: 1:05 PM
 */
?>

<?php
$_current_category = Mage::registry('current_category');

$_categories = Mage::getModel('catalog/category')
    ->getCollection()
    // magic is prepared here..
    ->addAttributeToSelect('*')
    // then the magic happens here:
    ->addAttributeToFilter('parent_id', array( $_current_category->getId()))
    ->addAttributeToFilter('is_active', 1)
    ->addAttributeToSort('position', 'asc')
    /*->addAttributeToFilter('level', array('eq'=>2))*/
    ->load();

    //isset filter param
    $filterParam = $this->getRequest()->getParam('filter');
    $counter = 0;
    if($_current_category->getId() == 121 && isset($filterParam)):
?>
    <?php if($filterParam == 'allrooms'): ?>
    <ul class="products-grid products-grid--max-2-col board-list">
    <?php
            $children = Mage::getModel('catalog/category')->getCategories($_current_category->getId());
            $i = 1;
            //for unrepeat behavior
            $boardsArray = array();
            $isRepeatted = false;

            foreach ($children as $subcategory):
                $boardsCollection = Mage::getResourceModel('validoc_board/board_collection')->addCategoryFilter($subcategory);
    ?>
                    <?php foreach ($boardsCollection as $_board): ?>
                        <?php $isRepeatted = false; ?>
                        <?php if($_board->getIsActive()): ?>
                            <?php $cur_board = Mage::getModel('validoc_board/board')->load($_board->getId()); ?>
                            <?php
                                //we check if board was printed
                                foreach ($boardsArray as $old) {
                                    if($_board->getId() == $old){
                                        $isRepeatted = true;
                                    }
                                }
                            ?>
                            <?php if($isRepeatted == false): ?>
                            <li class="grid12-6 <?php if($i%2 == 0) echo 'no-right-gutter'; else echo 'no-left-gutter';echo ($_board->getType() == 2) ? ' vignettes': ''; ?>">
                                <a href="<?php echo Mage::getUrl("designer-board/board/view",array("id"=>$cur_board->getId())); ?>" title="<?php echo $this->htmlEscape($cur_board->getName()) ?>" class="product-image">
                                    <?php $_imgSizeWidth = 450; ?>
                                    <?php $_imgSizeHeight = 275; ?>
                                    <img id="product-collection-image-<?php echo $cur_board->getId(); ?>"
                                    src="<?php echo $this->helper('validoc_board/image')->init($cur_board, 'small_image')->keepFrame(false)->resize($_imgSizeWidth,$_imgSizeHeight); ?>"
                                    alt="<?php echo $this->htmlEscape($cur_board->getName()) ?>" />
                                    <div class="product-info">
                                        <h2 class="product-name">
                                            <a href="<?php echo Mage::getUrl("designer-board/board/view",array("id"=>$cur_board->getId())); ?>" title="<?php echo $this->stripTags($cur_board->getName(), null, true) ?>">
                                                <?php echo $cur_board->getName(); ?>
                                            </a>
                                            <span><?php echo ' by '; ?></span>
                                            <?php if($_board->getType() == 2): ?>
                                                 <span class="firmname"><?php echo $cur_board->getDesigner()->getFirmName(); ?></span>
                                             <?php else: ?>
                                            <a href="<?php echo Mage::getUrl("designers/designer/view",array("id"=>$cur_board->getDesigner()->getId())); ?>" title="<?php echo $this->stripTags($cur_board->getDesigner()->getName(), null, true) ?>" class="owner">
                                                <?php echo $cur_board->getDesigner()->getName(); ?>
                                            </a>
                                            <span><?php echo ' of '; ?></span>
                                            <span class="firmname"><?php echo $cur_board->getDesigner()->getFirmName(); ?></span>
                                            <?php endif; ?>
                                        </h2>
                                    </div>
                                </a>
                            </li>
                            <?php endif;//isRepeatted ?>
                            <?php $counter = $i; ?>
                            <?php $i++; ?>
                        <?php endif;//isActive ?>
                        <?php
                            //we save in $boardsArray the $cur_board already printed
                            array_push($boardsArray, $cur_board->getId());
                        ?>
                    <?php endforeach;//boardsCollection ?>
    <?php
            endforeach;//children
            //var_dump($boardsArray);
            ?>
            <!-- last item browse by style link -->
                <?php
                    //sitting rooms filter
                    $isSittingsCat = Mage::registry('current_category');
                    $allRoomsP = array(
                        'id' => $isSittingsCat->getId(),
                    );
                    if($isSittingsCat->getId() == 121):
                ?>
                            <li class="grid12-6 no-right-gutter all-link-container" style="<?php echo ($counter % 2 == 0) ? 'display: none;' : 'display: block;'; ?>">
                                <a class="product-image all-rooms-link" href="<?php echo Mage::getUrl('catalog/category/view', $allRoomsP); ?>" title="Browse by style">
                                    <img src="<?php echo $this->getSkinUrl('images'); ?>/imgFondo.jpg">
                                        <h3>browse by style</h3>
                                </a>
                            </li>
                <?php endif;//isSittingCat ?>
        <?php
        endif;//if allrooms filter
    ?>
    </ul>
<?php
    else:
$_collectionSize = $_categories->count();
?>
    <?php if ($_collectionSize > 0) { ?>
        <div class="category-products boards-list decor-list">
            <?php // Grid Mode ?>
            <ul class="products-grid products-grid--max-2-col">
                <?php $i=1; foreach ($_categories as $_category): ?>
                    <?php if($_category->getIsActive()): ?>
                        <?php $cur_category = Mage::getModel('catalog/category')->load($_category->getId()); ?>
                        <?php if($_imageUrl = $cur_category->getThumbnail()): ?>
                            <li class="grid12-6 <?php if($i%2 == 0) echo 'no-right-gutter'; else echo 'no-left-gutter'; ?>">
                                <a href="<?php echo $_category->getUrl() ?>" title="<?php echo $this->htmlEscape($_category->getName()) ?>" class="product-image">
                                    <?php $_imgSizeWidth = 450; ?>
                                    <?php $_imgSizeHeight = 275; ?>
                                    <img id="product-collection-image-<?php echo $cur_category->getId(); ?>" src="<?php echo $this->getUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'catalog/category/' . $_imageUrl ?>" width="auto" alt="<?php echo $this->htmlEscape($_category->getName()) ?>" />
                                    <?php if($_current_category->getEntityId() == 129): ?>
                                        <h3><?php echo $cur_category->getName(); ?></h3>
                                    <?php endif; ?>
                                </a>
                            </li>
                            <?php $counter = $i; ?>
                        <?php $i++; endif ?>
                    <?php endif ?>
                <?php endforeach ?>
                <!-- last item view all styles link -->
                <?php
                    //sitting rooms filter
                    $isSittingsCat = Mage::registry('current_category');
                    $allRoomsP = array(
                        'id' => $isSittingsCat->getId(),
                        '_query' => array(
                            'filter' => 'allrooms'
                        )
                    );
                    if($isSittingsCat->getId() == 121):
                ?>
                            <li class="grid12-6 no-right-gutter all-link-container" style="<?php echo ($counter % 2 == 0) ? 'display: none;' : 'display: block;'; ?>">
                                <a class="product-image all-rooms-link" href="<?php echo Mage::getUrl('catalog/category/view', $allRoomsP); ?>" title="View all rooms">
                                    <img src="<?php echo $this->getSkinUrl('images'); ?>/imgFondo.jpg">
                                        <h3>view all styles</h3>
                                </a>
                            </li>
                <?php endif;//isSittingCat ?>
            </ul>


            <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>

        </div>
    <?php } ?>
<?php endif;//if isset filter param ?>

<div class="clearer"></div>