<?php
/**
 * Created by PhpStorm.
 * User: Juan Carlos
 * Date: 5/7/2015
 * Time: 1:05 PM
 */
?>

<?php
$_current_category = Mage::registry('current_category');

$_categories = Mage::getModel('catalog/category')
    ->getCollection()
    // magic is prepared here..
    ->addAttributeToSelect('*')
    // then the magic happens here:
    ->addAttributeToFilter('parent_id', array( $_current_category->getId()))
    ->addAttributeToFilter('is_active', 1)
    ->addAttributeToSort('position', 'asc')
    /*->addAttributeToFilter('level', array('eq'=>2))*/
    ->load();

$_collectionSize = $_categories->count();
?>
    <?php if ($_collectionSize > 0) { ?>
        <div class="category-products boards-list decor-list">
            <?php // Grid Mode ?>
            <ul class="products-grid products-grid--max-2-col">
                <?php $i=1; foreach ($_categories as $_category): ?>
                    <?php if($_category->getIsActive()): ?>
                        <?php $cur_category = Mage::getModel('catalog/category')->load($_category->getId()); ?>
                        <?php if($_imageUrl = $cur_category->getThumbnail()): ?>
                            <li class="grid12-6 <?php if($i%2 == 0) echo 'no-right-gutter'; else echo 'no-left-gutter'; ?>">
                                <a href="<?php echo $_category->getUrl() ?>" title="<?php echo $this->htmlEscape($_category->getName()) ?>" class="product-image">
                                    <?php $_imgSizeWidth = 450; ?>
                                    <?php $_imgSizeHeight = 275; ?>
                                    <img id="product-collection-image-<?php echo $cur_category->getId(); ?>" src="<?php echo $this->getUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'catalog/category/' . $_imageUrl ?>" width="auto" alt="<?php echo $this->htmlEscape($_category->getName()) ?>" />
                                    <?php if($_current_category->getEntityId() == 129): ?>
                                        <h3><?php echo $cur_category->getName(); ?></h3>
                                    <?php endif; ?>
                                </a>
                            </li>
                        <?php $i++; endif ?>
                    <?php endif ?>
                <?php endforeach ?>
            </ul>


            <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>

        </div>
    <?php } ?>

<div class="clearer"></div>