<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<div class="page-title blog-title <?php if (!$this->isFirstPage()): ?>not-<?php endif; ?>first-page<?php if ($this->isFirstPage() && $this->getTagLine()): ?> with-tagline<?php endif; ?>">
	<div id="title-header" class="span12">
		<div class="page-header">
			<section class="title-section">
				<h1><?php echo $this->escapeHtml($this->getBlogTitle()) ?></h1>
				<h2>The place where we write some words</h2>
			</section>
		</div> 
	</div>
</div>
<?php if ($this->isFirstPage() && $this->getTagLine()): ?>
	<p class="blog-desc blog-tag-line"><?php echo $this->escapeHtml($this->getTagLine()) ?></p>
<?php endif; ?>
<div class="blog-home">
	<?php echo $this->getPostListHtml() ?>
</div>
