<?php if (! Mage::getSingleton('customer/session')->isLoggedIn()): ?>
    <a href="<?php echo Mage::helper('customer')->getLoginUrl(); ?>" title="<?php echo $this->__('Sign In') ?>"><?php echo $this->__('Sign In') ?></a>
<?php //else: ?>
    <!-- <a href="<?php echo Mage::helper('customer')->getLogoutUrl(); ?>" title="<?php echo $this->__('Sign Out') ?>"><?php echo $this->__('Sign Out') ?></a> -->
<?php endif; ?>