<script>

function SubmitCreateForm()
{
	//check if msg is filled
	/*if (document.getElementById('description').value == '')	
		alert('<?php echo $this->__('Please fill description field'); ?>');
	else*/
		document.getElementById('form_create').submit();
}

</script>

<form id="form_create" name="form_create" method="POST" action="<?php echo $this->getSubmitUrl(); ?>">

<div class="page-title title-quote">
    <h1><?php echo $this->__('Request for a new quotation') ?></h1>
</div>

<h2><?php echo $this->__('1. Please review your quote') ?></h2>
<p>&nbsp;</p>
<table cellspacing="0" class="data-table" id="quotation-request-products">
<thead>
        <tr>
            <th><?php echo $this->__('Product') ?></th>
            <th width="100"><?php echo $this->__('Qty') ?></th>
        </tr>
</thead>
<tbody>
	<?php foreach($this->getCartProducts() as $item): ?>
		<?php if (($item->getProduct()->gettype_id() == 'simple') || ($item->getProduct()->gettype_id() == 'virtual') || ($item->getProduct()->gettype_id() == 'downloadable')): ?>
            <tr>
                <td class="product-name quote-page2">
                    <div class="product-img quote-page2">
                        <?php
                            $imageUrl = Mage::helper('catalog/image')->init($item->getProduct(), 'thumbnail');
                        ?>
                        <img src="<?php echo $imageUrl; ?>">
                    </div>
                	<a><?php echo $item->getName(); ?></a>
                	<?php echo $this->getProductOptions($item); ?>
                </td>
                <td width="100" class="product-qty"><input size="5" type="text" name="qty_<?php echo $item->getProduct()->getId(); ?>" id="qty_<?php echo $item->getProduct()->getId(); ?>" value="<?php echo $this->getItemQty($item); ?>" readonly></td>
            </tr>
        <?php endif; ?>
	<?php endforeach; ?>
</tbody>
</table>
<p>&nbsp;</p>

<!-- <h2><?php echo $this->__('2. Type your message') ?></h2>

<p>&nbsp;</p>

<center>
<textarea cols="110" rows="10" id="description" name="description"></textarea>
</center> -->

<p>&nbsp;</p>

<h2 class="send-us-inquiry-title"><?php echo $this->__('2. Send us your quote list') ?></h2>

<center>
<p style="margin-bottom: 50px;" class="inquiry-button-wrapper">
    <span class="legend">Personal quotes are provided within 72 hours via email</span>
    <button type="button" onclick="SubmitCreateForm();" title="Save" class="button"><span><span><?php echo $this->__('Submit quote request') ?></span></span></button>
</p>
</center>

</form>
<script type="text/javascript">
    var Handler = (function(){
        var dom = {
            headerTitle: '.title-quote h1'
        };
        var wrap = function(){
            //changing header content
            jQuery(dom.headerTitle).empty().html('My Quote List');
        };
        return {
            onReady: function(){
                wrap();
            }
        };
    })();
    jQuery(document).on('ready', Handler.onReady());
</script>