<?php
    $m = Mage::getModel("validoc_board/board");
    $floorplans = $m->getFloorplans($this->getBoard()->getId());
    $floorplan_products = array();
    foreach($floorplans as $f){
        $a = Mage::getModel('validoc_floorplan/floorplan')->load($f["floorplan_id"]);
        $b = $a->getSelectedProducts();
        foreach($b as $p){
            if(!isset($floorplan_products[$p->_data["entity_id"]]))
                $floorplan_products[$p->_data["entity_id"]] = $p->_data["quantity"];
        }
    }
    $productsId = array();
    foreach ($floorplan_products as $id => $qty) {
        array_push($productsId, $id);
    }

    $_board = $this->getBoard();
    $_designer = $this->getDesigner();
    $attributes = Mage::getSingleton('catalog/config')->getProductAttributes();
    $_productCollection = Mage::getModel('catalog/product')
                        ->getCollection()
                        ->addAttributeToSort('created_at', 'DESC')
                        ->addAttributeToFilter('entity_id',  array('in' => $productsId))
                        ->addAttributeToSelect($attributes)
                        ->load();

    if($_board->getType() == 2){
        $catIds = $m->getCustomCategoriesId($this->getBoard()->getId());
        if(!empty($catIds)){
            $ctf = array();//categories to filter
            foreach ($catIds as $k => $cat) {
                $ctf[]['finset'] = $cat;
            }
        }
        $_productCollection = Mage::getModel('catalog/product')
                            ->getCollection()
                            ->addAttributeToSelect('*')
                            ->joinField('category_id', 'catalog/category_product', 'category_id', 'product_id = entity_id', null, 'left')
                            ->addAttributeToFilter('category_id', array($ctf))
                            ->addAttributeToSort('created_at', 'DESC')
                            ->load();
    }//var_dump(count($_productCollection));//this gives 13

    $productsBoard = $_productCollection->getItems();

    $ghostAttributes = Mage::getSingleton('catalog/config')->getProductAttributes();
    $extrasCollection = Mage::getModel('catalog/product')
                            ->getCollection()
                            ->addAttributeToSort('created_at', 'DESC')
                            ->addAttributeToFilter('entity_id',  array('in' => $ghostProducts))
                            ->addAttributeToSelect($ghostAttributes)
                            ->load();

    $indexes = array_keys($productsBoard);

    if(array_key_exists(0, $indexes)){
        //2 elements per row
        $firstRow = array_slice($productsBoard, 0, 2);
    }
    if(array_key_exists(2, $indexes)){
        //3 elements per row
        $secondRow = array_slice($productsBoard, 2, 3);
    }
    if(array_key_exists(5, $indexes)){
        //3 elements per row
        $thirdRow = array_slice($productsBoard, 5, 3);
    }
    if(array_key_exists(8, $indexes)){
        //4 elements per row
        $fourthRow = array_slice($productsBoard, 8, 4);
    }
    if(array_key_exists(12, $indexes)){
        //3 elements per row
        $fiveRow = array_slice($productsBoard, 12, 3);
    }
    if(array_key_exists(15, $indexes)){
        //2 elements per row
        $sixRow = array_slice($productsBoard, 15, 2);
    }
    if(array_key_exists(17, $indexes)){
        //4 elements per row
        $sevenRow = array_slice($productsBoard, 17, 4);
    }
    if(array_key_exists(21, $indexes)){
        //2 elements per row
        $eightRow = array_slice($productsBoard, 21, 2);
    }
    if(array_key_exists(23, $indexes)){
        //4 elements per row
        $nineRow = array_slice($productsBoard, 23, 4);
    }
    if(array_key_exists(27, $indexes)){
        $tenRow = array_slice($productsBoard, 27, 3);
    }
    //getting product for design kit
    $designKitProducts = Mage::getModel('catalog/product')
                    ->getCollection()
                    ->addAttributeToSelect('*')
                    ->load()
                    ->getItems();
    $productDesign = null;
    foreach ($designKitProducts as $myproduct) {
        if(($myproduct->getAttributeText('design_kit') == 'Yes') && ( $myproduct->getBoardId() == $_board->getId())){
            $productDesign = $myproduct;
        }
    }

?>
<div id="messages_product_view">
    <?php
        //for custom system messages
        $lastProductId = Mage::getSingleton('checkout/session')->getLastAddedProductId(true);
        $productAdded = Mage::getModel('catalog/product')->load($lastProductId);
    ?>
</div>
<div class="product-view atp designer-board">
    <div class="product-essential">
        <?php
            $_helper = $this->helper('catalog/output');
            $boardCategoryIds = $_board->getCategoryIds();
            if(count($boardCategoryIds) > 0){
                $title_1 = '';
                $title_2 = '';
                $count = 0;
                foreach ($boardCategoryIds as $categoryId) {
                    if($count > 0){
                        $parent = Mage::getModel('catalog/category')->load($categoryId);
                        $title_2 .= ' | ' . $_helper->categoryAttribute($parent, $parent->getName(), 'name') . ' ' . $_helper->categoryAttribute($parent, $parent->getNameSuffix(), 'name_suffix');
                    }else {
                        $parent = Mage::getModel('catalog/category')->load($categoryId);
                        $title_1 .= $_helper->categoryAttribute($parent, $parent->getName(), 'name') . ' <span>' . $_helper->categoryAttribute($parent, $parent->getNameSuffix(), 'name_suffix') . '</span>  ';
                        $superParent = $parent->getParentCategory();
                    }
                    $count++;
                }
            }
        ?>
        <?php
            if($_board->getType() == 2){
                $title2 = "| " . Mage::getModel('catalog/category')->load($catIds[0]['category_id'])->getName();
            }else{
                $title2 = Mage::getSingleton('core/session')->getBoardTitle2();
            }
        ?>
        <div class="container-board">
            <div class="page-title">
                <h1>
                    <span class="title_1"><?php echo $superParent->getName()." <span>".$superParent->getNameSuffix()."</span>"; ?></span>
                    <span class="title_2"> <?php echo $title2; ?></span><!-- aca este span es -->
                </h1>
            </div>
            <?php
                if(isset($lastProductId)):
                    $msg = $this->__('%s was added to your shopping cart.', Mage::helper('core')->escapeHtml($productAdded->getName()));
            ?>
                <ul class="messages"><li class="success-msg"><ul><li><span><?php echo $msg; ?></span></li></ul></li></ul>
            <?php
                endif;
            ?>
            <div class="no-display">
                <input type="hidden" name="product" value="<?php echo $_board->getId() ?>" />
                <input type="hidden" name="related_product" id="related-products-field" value="" />
            </div>
        
            <div class="product-shop" style="display: none;">
                <div class="designer">
                    <?php
                    $_imgSize = 300;
                    Mage::log(Mage::helper('validoc_designer/image')->init($_designer, 'image'));
                    $_imageUrl = Mage::helper('validoc_designer/image')->init($_designer, 'image')->resize($_imgSize);
                    ?>
                    <img src="<?php echo $_imageUrl; ?>">
                </div>
                <div class="product-name">
                    <span class="h1"><?php echo $_designer->getName(); ?></span>
                </div>
                <div class="product-name">
                    <span class="h1"><?php echo $_board->getName(); ?></span>
                </div>

                <div class="price-info">
                    <?php echo $this->getPriceHtml($_board); ?>
                    <?php echo $this->getChildHtml('bundle_prices') ?>
                    <?php echo $this->getTierPriceHtml() ?>
                </div>

                <div class="extra-info">
                    <?php echo $this->getReviewsSummaryHtml($_board, 'default', false)?>
                    <?php echo $this->getChildHtml('product_type_availability'); ?>
                </div>

                <?php echo $this->getChildHtml('alert_urls') ?>

                <?php if ($_board->getShortDescription()):?>
                    <div class="short-description">
                        <div class="std"><?php echo nl2br($_board->getDescription()); ?></div>
                    </div>
                <?php endif;?>

                <?php echo $this->getChildHtml('other');?>

            </div>
        </div>

        <?php if($_board->getType() != 2): ?>
            <?php $bgImg = $this->getBackgroundImage(); ?>
            <div class="bg-box" <?php echo (($bgImg) ? 'style="background-image: url('.$bgImg->getUrl().');"' : ''); ?>>
                <div class="container-board">
                    <div class="product-img-box">
                        <?php echo $this->getChildHtml('media') ?>
                    </div>
                    <div class="product-name to-uppercase grid-container">
                    <h1><?php echo $_board->getName(); ?></h1>
                    </div>
                </div>

            </div>
        <?php endif; ?>
        
        <div class="container-board">    
            
            <div class="inner-container-board">
                <?php if($_board->getType() != 2): ?>
                    <div class="grid12-6 description-board">
                        <p><?php echo $_board->getDescription(); ?></p>
                        <a href="#" class="more-wrap"><span class="more">More ></span></a>
                    </div>
                    <!-- designer list -->
                    <div class="grid12-6 designers-list">
                        <div class="grid12-4 designer-img">
                            <?php
                            $_imgSize = 300;
                            Mage::log(Mage::helper('validoc_designer/image')->init($_designer, 'image'));
                            $_imageUrl = Mage::helper('validoc_designer/image')->init($_designer, 'image')->resize($_imgSize);
                            ?>
                            <img src="<?php echo $_imageUrl; ?>">
                        </div>
                        <div class="grid12-8 info">
                            <h4 class="Yesteryear title">Designer</h4>
                            <h5><?php echo $_designer->getName() ?> <br> <?php echo $_designer->getFirmName(); ?></h5>
                            <a href="<?php echo "/designers/designer/view/id/" . $_designer->getDesignerId(); ?>" class="more designer">See more designs from <?php echo $_designer->getName() ?> ></a>
                        </div>
                        <div class="clearer"></div>
                        <!-- get started -->
                        <div class="grid12-4 started">
                            <?php if(isset($productDesign)): ?>
                                <?php
                                    $designKitImage = Mage::getModel('catalog/product')->load($productDesign->getEntityId())->getMediaGalleryImages()->getItemByColumnValue('label', 'designkit');
                                    if(isset($designKitImage)){
                                        $myImage = $designKitImage['file'];
                                    }
                                ?>
                                <?php if(isset($myImage)): ?>
                                <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($myImage) ?>" alt="">
                                <?php endif; ?>
                            <?php else: ?>
                                <img src="<?php echo $this->getSkinUrl('images'); ?>/started-img.png">
                            <?php endif; ?>
                        </div>
                        <div class="grid12-8 info">
                            <h4 class="Yesteryear">Get started</h4>
                            <h5>order your custom fabric & design kit</h5>
                            <a href="#" id="<?php echo (isset($productDesign)) ? $productDesign->getEntityId() : ''; ?>" class="more">Learn more ></a>
                        </div>
                    </div>
                <?php endif; ?>
                <?php if($_board->getType() == 2): ?>
                    <h3 class="vignette-type">featured in <span class="board-name "><?php echo $_board->getName(); ?></span> by <span><?php echo $_designer->getFirmName(); ?></span></h3>
                <?php endif; ?>
                <?php $serializedGrid = $_board->getSerializedGrid(); ?>
                <?php if(empty($serializedGrid)): ?>
                <div class="products-list grid-container">
                    <!-- 8-4 per line -->
                    <?php if(isset($firstRow)): ?>
                    <div class="product-row 8-4-line">
                        <?php for($i = 0; $i < count($firstRow); $i++): ?>
                            <?php if($i == 0): ?>
                                <div class="grid12-8 on" id="<?php echo $firstRow[$i]->getEntityId(); ?>">
                                    <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($firstRow[$i]->getSmallImage()); ?>">
                                    <p class="image-name"><?php echo $firstRow[$i]->getName(); ?></p>
                                </div>
                            <?php endif; ?>
                            <?php if($i == 1): ?>
                                <div class="grid12-4 two" id="<?php echo $firstRow[$i]->getEntityId(); ?>">
                                    <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($firstRow[$i]->getSmallImage()); ?>" alt="">
                                    <p class="image-name"><?php echo $firstRow[$i]->getName(); ?></p>
                                </div>
                            <?php endif; ?>
                        <?php endfor; ?>
                    </div>
                    <?php endif; ?>

                    <!-- 3 per line -->
                    <?php if(isset($secondRow)): ?>
                    <div class="product-row 3-line">
                        <?php for($i = 0; $i < count($secondRow); $i++): ?>
                            <?php if($i == 0): ?>
                                <div class="grid12-4 three" id="<?php echo $secondRow[$i]->getEntityId(); ?>">
                                    <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($secondRow[$i]->getSmallImage()); ?>" alt="">
                                    <p class="image-name"><?php echo $secondRow[$i]->getName(); ?></p>
                                </div>
                            <?php endif; ?>
                            <?php if($i == 1): ?>
                                <div class="grid12-4 four" id="<?php echo $secondRow[$i]->getEntityId(); ?>">
                                    <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($secondRow[$i]->getSmallImage()); ?>" alt="">
                                    <p class="image-name"><?php echo $secondRow[$i]->getName(); ?></p>
                                </div>
                            <?php endif; ?>
                            <?php if($i == 2): ?>
                                <div class="grid12-4 five" id="<?php echo $secondRow[$i]->getEntityId(); ?>">
                                    <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($secondRow[$i]->getSmallImage()); ?>" alt="">
                                    <p class="image-name"><?php echo $secondRow[$i]->getName(); ?></p>
                                </div>
                            <?php endif; ?>
                        <?php endfor; ?>
                    </div>
                    <?php endif; ?>

                    <!-- 3 per line -->
                    <?php if(isset($thirdRow)): ?>
                    <div class="product-row 3-line">
                        <?php for($i = 0; $i < count($thirdRow); $i ++): ?>
                            <?php if($i == 0): ?>
                                <div class="grid12-4 six" id="<?php echo $thirdRow[$i]->getEntityId(); ?>">
                                    <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($thirdRow[$i]->getSmallImage()); ?>" alt="">
                                    <p class="image-name"><?php echo $thirdRow[$i]->getName(); ?></p>
                                </div>
                            <?php endif; ?>
                            <?php if($i == 1): ?>
                                <div class="grid12-4 seven" id="<?php echo $thirdRow[$i]->getEntityId(); ?>">
                                    <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($thirdRow[$i]->getSmallImage()); ?>" alt="">
                                    <p class="image-name"><?php echo $thirdRow[$i]->getName(); ?></p>
                                </div>
                            <?php endif; ?>
                            <?php if($i == 2): ?>
                                <div class="grid12-4 eight" id="<?php echo $thirdRow[$i]->getEntityId(); ?>">
                                    <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($thirdRow[$i]->getSmallImage()); ?>" alt="">
                                    <p class="image-name"><?php echo $thirdRow[$i]->getName(); ?></p>
                                </div>
                            <?php endif; ?>
                        <?php endfor; ?>
                    </div>
                    <?php endif; ?>

                    <!-- 4-8 per line -->
                    <?php if(isset($fourthRow)): ?>
                    <div class="product-row 4-8-line">
                        <?php for($i = 0; $i < count($fourthRow); $i++): ?>
                            <?php if($i == 0): ?>
                                <div class="grid12-4 nine big" id="<?php echo $fourthRow[$i]->getEntityId(); ?>">
                                    <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($fourthRow[$i]->getSmallImage()); ?>">
                                    <p class="image-name"><?php echo $fourthRow[$i]->getName(); ?></p>
                                </div>
                            <?php endif; ?>
                                <!-- <div class="grid12-8"> -->
                                    <?php if($i == 1): ?>
                                        <div class="ten" id="<?php echo $fourthRow[$i]->getEntityId(); ?>">
                                            <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($fourthRow[$i]->getSmallImage()); ?>">
                                            <p class="image-name"><?php echo $fourthRow[$i]->getName(); ?></p>
                                        </div>
                                    <?php endif; ?>
                                    <?php if($i == 2): ?>
                                        <div class="grid12-6 eleven" id="<?php echo $fourthRow[$i]->getEntityId(); ?>">
                                            <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($fourthRow[$i]->getSmallImage()); ?>">
                                            <p class="image-name"><?php echo $fourthRow[$i]->getName(); ?></p>
                                        </div>
                                    <?php endif; ?>
                                    <?php if($i == 3): ?>
                                        <div class="grid12-6 twelve" id="<?php echo $fourthRow[$i]->getEntityId(); ?>">
                                            <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($fourthRow[$i]->getSmallImage()); ?>">
                                            <p class="image-name"><?php echo $fourthRow[$i]->getName(); ?></p>
                                        </div>
                                    <?php endif; ?>
                                <!-- </div> -->
                        <?php endfor; ?>
                    </div>
                    <?php endif; ?>
                    <!-- 3 per line -->
                    <?php if(isset($fiveRow)): ?>
                    <div class="product-row 3-line">
                        <?php for($i = 0; $i < count($fiveRow); $i ++): ?>
                            <?php if($i == 0): ?>
                                <div class="grid12-4 thirteen" id="<?php echo $fiveRow[$i]->getEntityId(); ?>">
                                    <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($fiveRow[$i]->getSmallImage()); ?>" alt="">
                                    <p class="image-name"><?php echo $fiveRow[$i]->getName(); ?></p>
                                </div>
                            <?php endif; ?>
                            <?php if($i == 1): ?>
                                <div class="grid12-4 fourteen" id="<?php echo $fiveRow[$i]->getEntityId(); ?>">
                                    <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($fiveRow[$i]->getSmallImage()); ?>" alt="">
                                    <p class="image-name"><?php echo $fiveRow[$i]->getName(); ?></p>
                                </div>
                            <?php endif; ?>
                            <?php if($i == 2): ?>
                                <div class="grid12-4 fifteen" id="<?php echo $fiveRow[$i]->getEntityId(); ?>">
                                    <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($fiveRow[$i]->getSmallImage()); ?>" alt="">
                                    <p class="image-name"><?php echo $fiveRow[$i]->getName(); ?></p>
                                </div>
                            <?php endif; ?>
                        <?php endfor; ?>
                    </div>
                    <?php endif; ?>
                    <!-- 8-4 per line -->
                    <?php if(isset($sixRow)): ?>
                    <div class="product-row 8-4-line estito">
                        <?php for($i = 0; $i < count($sixRow); $i++): ?>
                            <?php if($i == 0): ?>
                                <div class="grid12-8 sixteen" id="<?php echo $sixRow[$i]->getEntityId(); ?>">
                                    <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($sixRow[$i]->getSmallImage()); ?>" alt="">
                                    <p class="image-name"><?php echo $sixRow[$i]->getName(); ?></p>
                                </div>
                            <?php endif; ?>
                            <?php if($i == 1): ?>
                                <div class="grid12-4 seventeen" id="<?php echo $sixRow[$i]->getEntityId(); ?>">
                                    <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($sixRow[$i]->getSmallImage()); ?>" alt="">
                                    <p class="image-name"><?php echo $sixRow[$i]->getName(); ?></p>
                                </div>
                            <?php endif; ?>
                        <?php endfor; ?>
                    </div>
                    <?php endif; ?>
                    <!-- 8-4 per line -->
                    <?php if(isset($sevenRow)): ?>
                    <div class="product-row 8-4-line">
                        <?php for($i = 0; $i < count($sevenRow); $i++): ?>
                        <!-- <div class="grid12-8"> -->
                            <?php if($i == 0): ?>
                                <div class="grid12-6 nineteen" id="<?php echo $sevenRow[$i]->getEntityId(); ?>">
                                    <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($sevenRow[$i]->getSmallImage()); ?>">
                                    <p class="image-name"><?php echo $sevenRow[$i]->getName(); ?></p>
                                </div>
                            <?php endif; ?>
                            <?php if($i == 1): ?>
                                <div class="grid12-6 twenty" id="<?php echo $sevenRow[$i]->getEntityId(); ?>">
                                    <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($sevenRow[$i]->getSmallImage()); ?>">
                                    <p class="image-name"><?php echo $sevenRow[$i]->getName(); ?></p>
                                </div>
                            <?php endif; ?>
                            <?php if($i == 2): ?>
                                <div class="eighteen" id="<?php echo $sevenRow[$i]->getEntityId(); ?>">
                                    <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($sevenRow[$i]->getSmallImage()); ?>">
                                    <p class="image-name"><?php echo $sevenRow[$i]->getName(); ?></p>
                                </div>
                            <?php endif; ?>
                        <!-- </div> -->
                        <?php if($i == 3): ?>
                            <div class="grid12-4 twenty-one big" id="<?php echo $sevenRow[$i]->getEntityId(); ?>">
                                <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($sevenRow[$i]->getSmallImage()); ?>">
                                <p class="image-name"><?php echo $sevenRow[$i]->getName(); ?></p>
                            </div>
                        <?php endif; ?>
                        <?php endfor; ?>
                    </div>
                    <?php endif; ?>
                    <!-- 4-8 per line -->
                    <?php if(isset($eightRow)): ?>
                    <div class="product-row 4-8-line">
                    <?php for($i = 0; $i < count($eightRow); $i++): ?>
                        <?php if($i == 0): ?>
                            <div class="grid12-4 twenty-two" id="<?php echo $eightRow[$i]->getEntityId(); ?>">
                                <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($eightRow[$i]->getSmallImage()); ?>" alt="">
                                <p class="image-name"><?php echo $eightRow[$i]->getName(); ?></p>
                            </div>
                        <?php endif; ?>
                        <?php if($i == 1): ?>
                            <div class="grid12-8 twenty-three" id="<?php echo $eightRow[$i]->getEntityId(); ?>">
                                <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($eightRow[$i]->getSmallImage()); ?>" alt="">
                                <p class="image-name"><?php echo $eightRow[$i]->getName(); ?></p>
                            </div>
                        <?php endif; ?>
                        <?php endfor; ?>
                    </div>
                    <?php endif; ?>
                    <!-- 8-4 per line -->
                    <?php if(isset($nineRow)): ?>
                    <div class="product-row 8-4-line">
                    <?php for($i = 0; $i < count($nineRow); $i++): ?>
                        <!-- <div class="grid12-8"> -->
                            <?php if($i == 0): ?>
                                <div class="twenty-four" id="<?php echo $nineRow[$i]->getEntityId(); ?>">
                                    <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($nineRow[$i]->getSmallImage()); ?>">
                                    <p class="image-name"><?php echo $nineRow[$i]->getName(); ?></p>
                                </div>
                            <?php endif; ?>
                            <?php if($i == 1): ?>
                                <div class="grid12-6 twenty-five" id="<?php echo $nineRow[$i]->getEntityId(); ?>">
                                    <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($nineRow[$i]->getSmallImage()); ?>">
                                    <p class="image-name"><?php echo $nineRow[$i]->getName(); ?></p>
                                </div>
                            <?php endif; ?>
                            <?php if($i == 2): ?>
                                <div class="grid12-6 twenty-six" id="<?php echo $nineRow[$i]->getEntityId(); ?>">
                                    <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($nineRow[$i]->getSmallImage()); ?>">
                                    <p class="image-name"><?php echo $nineRow[$i]->getName(); ?></p>
                                </div>
                            <?php endif; ?>
                        <!-- </div> -->
                        <?php if($i == 3): ?>
                            <div class="grid12-4 twenty-seven big"  id="<?php echo $nineRow[$i]->getEntityId(); ?>">
                                <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($nineRow[$i]->getSmallImage()); ?>">
                                <p class="image-name"><?php echo $nineRow[$i]->getName(); ?></p>
                            </div>
                        <?php endif; ?>
                    <?php endfor; ?>
                    </div>
                    <?php endif; ?>
                    <!-- 3 per line -->
                    <?php if(isset($tenRow)): ?>
                    <div class="product-row 3-line">
                    <?php for($i = 0; $i < count($tenRow); $i++): ?>
                        <?php if($i == 0): ?>
                            <div class="grid12-4 twenty-eight" id="<?php echo $tenRow[$i]->getEntityId(); ?>">
                                <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($tenRow[$i]->getSmallImage()); ?>" alt="">
                                <p class="image-name"><?php echo $tenRow[$i]->getName(); ?></p>
                            </div>
                        <?php endif; ?>
                        <?php if($i == 1): ?>
                            <div class="grid12-4 twenty-nine" id="<?php echo $tenRow[$i]->getEntityId(); ?>">
                                <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($tenRow[$i]->getSmallImage()); ?>" alt="">
                                <p class="image-name"><?php echo $tenRow[$i]->getName(); ?></p>
                            </div>
                        <?php endif; ?>
                        <?php if($i == 2): ?>
                            <div class="grid12-4 thirty" id="<?php echo $tenRow[$i]->getEntityId(); ?>">
                                <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($tenRow[$i]->getSmallImage()); ?>" alt="">
                                <p class="image-name"><?php echo $tenRow[$i]->getName(); ?></p>
                            </div>
                        <?php endif; ?>
                        <?php endfor; ?>
                    </div>
                    <?php endif; ?>

                    <?php
                        $i = 30;
                        while(array_key_exists($i, $indexes)):
                            $genericRow = array_slice($productsBoard, $i, 3);
                    ?>
                            <div class="product-row 3-line extra">
                                <?php for($j = 0; $j < count($genericRow); $j++): ?>
                                    <div class="grid12-4"  id="<?php echo $genericRow[$j]->getEntityId(); ?>">
                                        <?php //var_dump($genericRow[$j]); ?>
                                        <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($genericRow[$j]->getSmallImage()); ?>" alt="">
                                        <p class="image-name"><?php echo $genericRow[$j]->getName(); ?></p>
                                    </div>
                                <?php endfor; ?>
                            </div>
                    <?php
                        $i = $i + 3;
                        endwhile;
                    ?>
                </div>
                <?php else://there is grid customization ?>
                    <?php
                        $savedGrid = $_board->getSerializedGrid();
                        $savedGrid = json_decode($savedGrid, true);
                        $savedGrid = json_decode($savedGrid, true);
                    ?>
                        <div class="products-list grid-container gridster">
                            <div class="inner">
                                <?php foreach($savedGrid as $cell): ?>
                                    <div id="<?php echo $cell['id']; ?>" data-row="<?php echo $cell['row']; ?>" data-col="<?php echo $cell['col']; ?>" data-sizex="<?php echo $cell['size_x']; ?>" data-sizey="<?php echo $cell['size_y']; ?>">
                                        <?php foreach($productsBoard as $item): ?>
                                            <?php if($cell['id'] == $item->getEntityId()): ?>
                                                <?php
                                                    $gridImg = Mage::getModel('catalog/product')->load($item->getEntityId())->getMediaGalleryImages()->getItemByColumnValue('label', 'grid');
                                                    if(!isset($gridImg))://it keeps the base image
                                                        $sameProduct = Mage::getModel('catalog/product')->load($item->getEntityId());
                                                ?>
                                                        <img src="<?php echo Mage::helper('catalog/image')->init($sameProduct, 'image'); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true); ?>" />
                                                <?php
                                                    else://select the grid image
                                                        $pImage = $gridImg['file'];
                                                ?>
                                                        <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($pImage) ?>" alt="">
                                                <?php
                                                    endif;
                                                ?>
                                                <p class="image-name"><?php
                                                        //echo $item->getname();
                                                        $_product = Mage::getModel('catalog/product')->load($item->getEntityId());
                                                        $manufacturerPiece = $_product->getAttributeText('manufacturer_pieces');
                                                        if(isset($manufacturerPiece))
                                                            echo $manufacturerPiece;
                                                    ?>
                                                    <?php
                                                        //manufacturer name
                                                        $_productId = $item->getEntityId();
                                                        $_product = Mage::getModel('catalog/product')->load($_productId);
                                                        $_manufacturerName = $_product->getAttributeText('manufacturer');
                                                        if(isset($_manufacturerName) && $_manufacturerName != false)
                                                            echo " <span class='separator-name'>|</span> ".$_manufacturerName;
                                                    ?>
                                                </p>
                                            <?php endif; ?>
                                        <?php endforeach; ?>
                                        <?php //extra products ?>
                                        <?php foreach($extrasCollection->getItems() as $gp): ?>
                                            <div id="<?php echo $gp->getEntityId(); ?>" data-row="<?php echo $k; ?>" data-col="<?php echo $l; ?>" data-sizex="1" data-sizey="1">
                                                <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($gp->getSmallImage()); ?>">
                                                <p class="image-name hereIs">
                                                    <?php
                                                        $_product = Mage::getModel('catalog/product')->load($gp->getEntityId());
                                                        $manufacturerPiece = $_product->getAttributeText('manufacturer_pieces');
                                                        if(isset($manufacturerPiece))
                                                            echo $manufacturerPiece;
                                                    ?>
                                                    <?php
                                                        $_productId = $gp->getEntityId();
                                                        $_product = Mage::getModel('catalog/product')->load($_productId);
                                                        $_manufacturerName = $_product->getAttributeText('manufacturer');
                                                        if(isset($_manufacturerName) && $_manufacturerName != false)
                                                            echo " <span class='separator-name'>|</span>".$_manufacturerName;
                                                    ?>
                                                </p>
                                            </div>
                                            <?php
                                                $l++;
                                                if($l == 4){
                                                    $k++;
                                                    $l = 1;
                                                }
                                            ?>
                                        <?php endforeach; ?>
                                    </div>
                                <?php endforeach; ?>
                            </div>
                        </div>
                <?php endif; ?>
                <?php foreach($productsBoard as $key => $_product): ?>
                    <div class="container popup rooms" id="popup-<?php echo $_product->getEntityId(); ?>" style="display: none;">
                        <?php
                            $mainImg = null;
                            $images = Mage::getModel('catalog/product')->load($_product->getEntityId())->getMediaGalleryImages();
                            $counter=0;
                            foreach ($images as $img) {
                                if(($img['label']== 'popup')&&($counter==0)) {
                                    $mainImg = $img;
                                    $counter++;
                                }
                            }
                        ?>
                        <div class="grid12-6 popup-images">
                            <div class="main-img">
                                <?php if($mainImg): ?>
                                    <img src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail', $mainImg['file']); ?>">
                                <?php else: ?>
                                    <img src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail', $_product->getImage()); ?>" alt="">
                                <?php endif; ?>
                            </div>
                            <div class="extra-imgs">
                                <ul>
                                    <?php foreach($images as $img): ?>
                                        <?php if($img['label'] == 'popup'): ?>
                                            <li>
                                                <img src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail', $img['file']); ?>" alt="">
                                            </li>
                                        <?php endif; ?>
                                    <?php endforeach; ?>
                                </ul>
                            </div>
                        </div>
                        <div class="grid12-6 popup-info">
                            <h2><?php echo $_product->getName(); ?></h2>
                            <p>featured in <span>
                                <?php
                                    $prod = Mage::getModel('catalog/product')->load($_product->getEntityId());
                                    $rooms = $prod->getBoardId();
                                    if(!empty($rooms)){
                                        $roomIds = explode(",", $rooms);
                                        $boardsCollection = array();
                                        foreach ($roomIds as $key => $roomId) {
                                            $board = Mage::getModel('validoc_board/board')->load($roomId);
                                            array_push($boardsCollection, $board);
                                        }
                                    }
                                    foreach ($boardsCollection as $key => $board) {
                                        echo '<a class="popup-link" href="'.Mage::getBaseUrl().'designer-board/board/view/id/'.$board->getBoardId().'">'.$board->getName();
                                        if($key != count($boardsCollection)-1){
                                            echo "</a>, ";
                                        }else{
                                            echo "</a>";
                                        }
                                    }
                                    $firstBoard = $boardsCollection[0];
                                ?>
                            </span></p>
                            <p class="description"><?php echo $_product->getShortDescription(); ?></p>
                            <p class="description dimensions"><?php echo $_product->getDimensions(); ?></p>
                            <p class="description arrival" style="display: none;">ESTIMATED ARRIVAL: <?php echo $_product->getEstimatedArrival(); ?></p>
                            <?php
                                $same2 = Mage::getModel('catalog/product')->load($_product->getEntityId());
                                $amazonUrl = $same2->getAmazonUrl();
                            ?>
                            <?php if(empty($amazonUrl)): ?>
                                <p class="description upon">PRICE UPON REQUEST</p>
                            <?php endif; ?>

                            <div class="actions clearer<?php echo $actionsClasses; ?> shop">
                                    <?php //Cart button ?>
                                    <?php
                                        $sameProduct = Mage::getModel('catalog/product')->load($_product->getEntityId());
                                    ?>
                                        <?php if ($_product->isSaleable()): ?>
                                            <?php if($sameProduct->getAmazonUrl()): ?>
                                            <div class="amazon-link">
                                                <?php echo $sameProduct->getAmazonUrl(); ?>
                                                <a href="#" class="buy-amazon" target="_blank"><img src="<?php echo $this->getSkinUrl('images'); ?>/amazon-button.png"></a>
                                            </div>
                                        <?php else: ?>
                                            <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->helper('checkout/cart')->getAddUrl($_product) ?>')"><span><span><?php echo $this->__('add to my quote list') ?></span></span></button>
                                        <?php endif; ?>
                                        <?php else: ?>
                                            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                        <?php endif; ?>
                                </div>
                        </div>
                    </div><!-- container popup rooms -->
                <?php endforeach; ?>
                <?php //extras collection, $extrasCollection->getItems() ?>
                <?php foreach($extrasCollection->getItems() as $_product): ?>
                    <div class="container popup extras" id="popup-<?php echo $_product->getEntityId(); ?>" style="display: none;">
                        <?php
                            $mainImg = null;
                            $images = Mage::getModel('catalog/product')->load($_product->getEntityId())->getMediaGalleryImages();
                            $counter=0;
                            foreach ($images as $img) {
                                if(($img['label']== 'popup')&&($counter==0)) {
                                    $mainImg = $img;
                                    $counter++;
                                }
                            }
                        ?>
                        <div class="grid12-6 popup-images">
                            <div class="main-img">
                                <?php if($mainImg): ?>
                                    <img src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail', $mainImg['file']); ?>">
                                <?php else: ?>
                                    <img src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail', $_product->getImage()); ?>" alt="">
                                <?php endif; ?>
                            </div>
                            <div class="extra-imgs">
                                <ul>
                                    <?php foreach($images as $img): ?>
                                        <?php if($img['label'] == 'popup'): ?>
                                            <li>
                                                <img src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail', $img['file']); ?>" alt="">
                                            </li>
                                        <?php endif; ?>
                                    <?php endforeach; ?>
                                </ul>
                            </div>
                        </div>
                        <div class="grid12-6 popup-info">
                            <h2><?php echo $_product->getName(); ?></h2>
                            <p>featured in <span>
                                <?php
                                    $prod = Mage::getModel('catalog/product')->load($_product->getEntityId());
                                    $rooms = $prod->getBoardId();
                                    if(!empty($rooms)){
                                        $roomIds = explode(",", $rooms);
                                        $boardsCollection = array();
                                        foreach ($roomIds as $key => $roomId) {
                                            $board = Mage::getModel('validoc_board/board')->load($roomId);
                                            array_push($boardsCollection, $board);
                                        }
                                    }
                                    foreach ($boardsCollection as $key => $board) {
                                        echo '<a class="popup-link" href="'.Mage::getBaseUrl().'designer-board/board/view/id/'.$board->getBoardId().'">'.$board->getName();
                                        if($key != count($boardsCollection)-1){
                                            echo "</a>, ";
                                        }else{
                                            echo "</a>";
                                        }
                                    }
                                    $firstBoard = $boardsCollection[0];
                                ?>
                            </span></p>
                            <p class="description"><?php echo $_product->getShortDescription(); ?></p>
                            <p class="description dimensions"><?php echo $_product->getDimensions(); ?></p>
                            <p class="description arrival" style="display: none;">ESTIMATED ARRIVAL: <?php echo $_product->getEstimatedArrival(); ?></p>
                            <?php
                                $same2 = Mage::getModel('catalog/product')->load($_product->getEntityId());
                                $amazonUrl = $same2->getAmazonUrl();
                            ?>
                            <?php if(empty($amazonUrl)): ?>
                                <p class="description upon">PRICE UPON REQUEST</p>
                            <?php endif; ?>

                            <div class="actions clearer<?php echo $actionsClasses; ?> shop">
                                    <?php //Cart button ?>
                                    <?php
                                        $sameProduct = Mage::getModel('catalog/product')->load($_product->getEntityId());
                                    ?>
                                        <?php if ($_product->isSaleable()): ?>
                                            <?php if($sameProduct->getAmazonUrl()): ?>
                                            <div class="amazon-link">
                                                <?php echo $sameProduct->getAmazonUrl(); ?>
                                                <a href="#" class="buy-amazon" target="_blank"><img src="<?php echo $this->getSkinUrl('images'); ?>/amazon-button.png"></a>
                                            </div>
                                        <?php else: ?>
                                            <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->helper('checkout/cart')->getAddUrl($_product) ?>')"><span><span><?php echo $this->__('add to my quote list') ?></span></span></button>
                                        <?php endif; ?>
                                        <?php else: ?>
                                            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                        <?php endif; ?>
                                </div>
                        </div>
                    </div><!-- container extras -->
                <?php endforeach; ?>
                <?php if(isset($productDesign)): ?>
                    <div class="container popup design-kit" id="popup-<?php echo $productDesign->getEntityId();  ?>" style="display: none;">
                        <?php
                            $mainImg = null;
                            $images = Mage::getModel('catalog/product')->load($productDesign->getEntityId())->getMediaGalleryImages();
                            $counter=0;
                            foreach ($images as $img) {
                                if(($img['label']== 'popup')&&($counter==0)) {
                                    $mainImg = $img;
                                    $counter++;
                                }
                            }
                        ?>
                        <div class="grid12-6 popup-images">
                            <div class="main-img">
                                <?php if($mainImg): ?>
                                    <img src="<?php echo $this->helper('catalog/image')->init($productDesign, 'thumbnail', $mainImg['file']); ?>">
                                <?php else: ?>
                                    <img src="<?php echo $this->helper('catalog/image')->init($productDesign, 'thumbnail', $productDesign->getImage()); ?>" alt="">
                                <?php endif; ?>
                            </div>
                            <div class="extra-imgs">
                                <ul>
                                    <?php foreach($images as $img): ?>
                                        <?php if($img['label'] == 'popup'): ?>
                                            <li>
                                                <img src="<?php echo $this->helper('catalog/image')->init($productDesign, 'thumbnail', $img['file']); ?>" alt="">
                                            </li>
                                        <?php endif; ?>
                                    <?php endforeach; ?>
                                </ul>
                            </div>
                        </div>
                        <div class="grid12-6 popup-info">
                            <h2><?php echo $productDesign->getName(); ?></h2>
                            <p>for <span>
                                <?php
                                    $prod = Mage::getModel('catalog/product')->load($productDesign->getEntityId());
                                    $rooms = $prod->getBoardId();
                                    if(!empty($rooms)){
                                        $roomIds = explode(",", $rooms);
                                        $boardsCollection = array();
                                        foreach ($roomIds as $key => $roomId) {
                                            $board = Mage::getModel('validoc_board/board')->load($roomId);
                                            array_push($boardsCollection, $board);
                                        }
                                    }
                                    foreach ($boardsCollection as $key => $board) {
                                        echo '<a class="popup-link" href="'.Mage::getBaseUrl().'designer-board/board/view/id/'.$board->getBoardId().'">'.$board->getName();
                                        if($key != count($boardsCollection)-1){
                                            echo "</a>, ";
                                        }else{
                                            echo "</a>";
                                        }
                                    }
                                    $firstBoard = $boardsCollection[0];
                                ?>
                            </span></p>
                            <p class="description"><?php echo $productDesign->getShortDescription(); ?></p>
                            <p class="description dimensions"><?php echo $productDesign->getDimensions(); ?></p>
                            <p class="description arrival" style="display: none;">ESTIMATED ARRIVAL: <?php echo $productDesign->getEstimatedArrival(); ?></p>
                            <!-- <p class="description upon">PRICE UPON REQUEST</p> -->
                            <div class="actions clearer<?php echo $actionsClasses; ?> shop">
                                    <?php //Cart button ?>
                                    <?php
                                        $sameProduct = Mage::getModel('catalog/product')->load($productDesign->getEntityId());
                                    ?>
                                        <?php if ($productDesign->isSaleable()): ?>
                                            <?php if($sameProduct->getAmazonUrl()): ?>
                                            <div class="amazon-link">
                                                <?php echo $sameProduct->getAmazonUrl(); ?>
                                                <a href="#" class="buy-amazon" target="_blank"><img src="<?php echo $this->getSkinUrl('images'); ?>/amazon-button.png"></a>
                                            </div>
                                        <?php else: ?>
                                            <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->helper('checkout/cart')->getAddUrl($productDesign) ?>')"><span><span><?php echo $this->__('add to my quote list') ?></span></span></button>
                                        <?php endif; ?>
                                        <?php else: ?>
                                            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                        <?php endif; ?>
                                </div>
                        </div>
                    </div><!-- container popup design kit -->
                <?php endif; ?>


                <?php echo $this->getChildHtml('related_products') ?>

                <?php echo $this->getChildHtml('board_related_products') ?>
                <div class="clearer"></div>
            </div>
        </div>
    </div>



    <?php echo $this->getChildHtml('upsell_products') ?>
    <?php echo $this->getChildHtml('product_additional_data') ?>

</div>
<style>
    
    #carouselInspirationContent .owl-controls .owl-buttons div{
        background-image: none !important;
    text-indent: 0;

    /* Font icons */
    display: inline-block;
    font-family: ThemeIcons;
    font-style: normal;
    font-weight: normal;
    font-variant: normal;
    text-transform: none;
    /*line-height: 1em;*/ /* Important: don't overrid line height, it depends on the size of the icon */
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;

    /* Icon size */
    font-size: 50px;
    position: absolute;
    color: #fff;

    }

    #carouselInspirationContent .owl-controls .owl-buttons .owl-prev{
         left:0; top:48%;
    }
    #carouselInspirationContent .owl-controls .owl-buttons .owl-next{
         right:0; top:48%;
    }
</style>
<script type="text/javascript">
    jQuery(document).ready(function(){
        //Slider Inspiration
        jQuery('#carouselInspiration').owlCarousel({
          navigation : true,
          pagination : false,
          slideSpeed : 300,
          autoPlay : false,
          stopOnHover : true,
          paginationSpeed : 400,
          singleItem:true,
          items : 1,
          transitionStyle : "fade",
          navigationText : ['','']
        });
        //Slider Inspiration Thumbs Events
        jQuery('.product-image-thumbs li a').on('click',function(e){
            e.preventDefault();
            if(jQuery(this).hasClass('inspiration')){
                jQuery('#carouselInspirationContent').removeAttr('style');
                jQuery('#image-main').css('display','none');
            }else{
                var src = jQuery(this).find('img').attr('src');
                jQuery('#image-main').removeAttr('style');
                jQuery('#image-main').attr('src', src);
                jQuery('#carouselInspirationContent').css('display','none');
            }
        });
        jQuery('.rooms-floorplans li a').unbind('click');
    });
    
    //popup behavior
    jQuery('.grid-container .inner > div, .grid-container .product-row > div, .designers-list .info .more:not(.designer)').on('click',  function(e){
        e.preventDefault();
        var target = jQuery(this).attr('id');
        if(target.length === 0){
            return;
        }
        jQuery('.page-title.category-title h1 span.title_1').css('z-index', 'auto');
        jQuery('.logo.logo--regular, #nav, .footer-container').css('z-index', '9');
        jQuery('.grid-container .inner > div, .grid-container .product-row > div, .designers-list .info .more:not(.designer)').fancybox({
            href: '#popup-' + target,
            titleShow: false,
            transitionIn: 'elastic',
            transitionOut: 'elastic',
            autoscale: true,
            scrolling: 'no',
            maxWidth: 800,
            maxHeight: 550,
            width: '100%',
            height: 550,
            autoSize: false,
            afterClose: function(){
                jQuery('.logo.logo--regular, #nav, .footer-container, .sticky-container, .footer-container').removeAttr('style');
                jQuery('.page-title.category-title h1 span.title_1').removeAttr('style');
                jQuery('.container-board .product-name.to-uppercase.grid-container').css('z-index', '100');
            },
            beforeShow: function(){
                jQuery('#nav, .sticky-container, .footer-container').css('z-index', '5');
                jQuery('.logo.logo--regular').css('z-index', '6');
                jQuery('.container-board .product-name.to-uppercase.grid-container').css('z-index', 'auto');
            }
        });
        //change imgs
        jQuery('.extra-imgs ul li img').click(function(){
            var mainParentContainer = jQuery(this).parent().parent().parent().parent().parent();
            mainParentContainer.find('.main-img').find('img').attr('src', jQuery(this).attr('src'));
        });
    });
    jQuery('.designers-list .started img').on('click', function(e){
        e.preventDefault();
        jQuery('.designers-list .info .more:not(.designer)').click();
    });
    //setting time to magento messages
    if(jQuery('.messages').length > 0){
        jQuery('.messages').delay(6000).slideUp(500);
    }
    //equalizer
    jQuery('.product-row div:not(.big)').equalizer({
        min: 226,
        max: 226,
        columns: '> img',
    });
    jQuery('.product-row div.big').equalizer({
        min: 603,
        max: 603,
        columns: '> img',
    });
    <?php $serializedGrid = $_board->getSerializedGrid(); ?>
    <?php if(!empty($serializedGrid)): ?>
        var gridster = jQuery('.products-list .inner').gridster({
            max_cols: 3,
            widget_margins: [20, 60],
            widget_base_dimensions: [300, 300],
            widget_selector: "div",
            resize: {
                enabled: false
            }
        }).data('gridster');
        gridster.disable();
    <?php endif; ?>
    //height of quote section
        quoteContent = jQuery('.designer-board .description-board p').text();
        maxLength = 129;
        if(jQuery.trim(quoteContent).length > maxLength){
            jQuery('.designer-board .description-board .more-wrap').css('display', 'inline');
            var newStr = quoteContent.substring(0, maxLength);
            var removedStr = quoteContent.substring(maxLength, jQuery.trim(quoteContent).length);
            var dots = jQuery('<span class="dots">...</span>');
            jQuery('.designer-board .description-board p').empty().html(newStr).append(dots);
            jQuery('.designer-board .description-board').css('background-position', '6% 0, 94% 87%');
            jQuery('.designer-board .description-board p').append('<span class="more-text">' + removedStr + '</span>');
        }else{
            jQuery('.designer-board .description-board .more-wrap').css('display', 'none');
            jQuery('.designer-board .description-board').css('background-position', '6% 0, 94% 95%');
        }

        jQuery('.designer-board .description-board .more').on('click', function(){
            if(jQuery(this).hasClass('open')){
                jQuery(this).text('More >').removeClass('open');
                newStr = quoteContent.substring(0, maxLength);
                var removedStr = quoteContent.substring(maxLength, jQuery.trim(quoteContent).length);
                var dots = jQuery('<span class="dots">...</span>');
                jQuery('.designer-board .description-board p').empty().html(newStr).append(dots);
                jQuery('.designer-board .description-board').css('background-position', '6% 0, 94% 87%');
                jQuery('.designer-board .description-board p').append('<span class="more-text">' + removedStr + '</span>');
            }else{
                jQuery(this).text('Less >').addClass('open');
                jQuery('.designer-board .description-board p .dots').remove();
                jQuery('.designer-board .description-board').css('background-position', '6% 0, 94% 92%');
                jQuery('.designer-board .description-board p .more-text').contents().unwrap();
            }
            return false;
        });
    //buy from amazon link
        jQuery('.amazon-link').each(function(){
            amazonLink = jQuery(this).find(jQuery('a:not(.buy-amazon)')).attr('href');
            jQuery(this).find(jQuery('.buy-amazon')).attr('href', amazonLink);
        });
</script>

