<?php
/**
 * Designer floorplan view template
 *
 * @see Validoc_Floorplan_Block_Detail_View
 */

    $_floorplan = $this->getFloorplan();
    $_designer = $this->getDesigner();
    $_floorplan_products = $this->getFloorplanProducts();

    $productsId = array();
    foreach ($_floorplan_products as $id => $qty) {
        array_push($productsId, $id);
    }
    $attributes = Mage::getSingleton('catalog/config')->getProductAttributes();
    $_productCollection = Mage::getModel('catalog/product')
                            ->getCollection()
                            ->addAttributeToSort('created_at', 'DESC')
                            ->addAttributeToFilter('entity_id',  array('in' => $productsId))
                            ->addAttributeToSelect($attributes)
                            ->load();

    $productsFloorplan = $_productCollection->getItems();
    //total
    $totalPrice = 0;
    foreach ($productsFloorplan as $p) {
        $totalPrice = $totalPrice + $p->getPrice();
    }

    $indexes = array_keys($productsFloorplan);

    if(array_key_exists(0, $indexes)){
        //2 elements per row
        $firstRow = array_slice($productsFloorplan, 0, 2);
    }
    if(array_key_exists(2, $indexes)){
        //3 elements per row
        $secondRow = array_slice($productsFloorplan, 2, 3);
    }
    if(array_key_exists(5, $indexes)){
        //3 elements per row
        $thirdRow = array_slice($productsFloorplan, 5, 3);
    }
    if(array_key_exists(8, $indexes)){
        //4 elements per row
        $fourthRow = array_slice($productsFloorplan, 8, 4);
    }
    if(array_key_exists(12, $indexes)){
        //3 elements per row
        $fiveRow = array_slice($productsFloorplan, 12, 3);
    }
    if(array_key_exists(15, $indexes)){
        //2 elements per row
        $sixRow = array_slice($productsFloorplan, 15, 2);
    }
    if(array_key_exists(17, $indexes)){
        //4 elements per row
        $sevenRow = array_slice($productsFloorplan, 17, 4);
    }
    if(array_key_exists(21, $indexes)){
        //2 elements per row
        $eightRow = array_slice($productsFloorplan, 21, 2);
    }
    if(array_key_exists(23, $indexes)){
        //4 elements per row
        $nineRow = array_slice($productsFloorplan, 23, 4);
    }
    if(array_key_exists(27, $indexes)){
        $tenRow = array_slice($productsFloorplan, 27, 3);
    }

?>
<div id="messages_product_view">
    <?php
        //for custom system messages
        $lastProductId = Mage::getSingleton('checkout/session')->getLastAddedProductId(true);
        $productAdded = Mage::getModel('catalog/product')->load($lastProductId);
    ?>
</div>
<div class="product-view atp designer-floorplan">
    <div class="product-essential">
        <?php
            $board = $this->getBoard();
            $_helper = $this->helper('catalog/output');
            $floorplanCategoryIds = $board->getCategoryIds();
            if(count($floorplanCategoryIds) > 0){
                $title_1 = '';
                $title_2 = '';
                $count = 0;
                foreach ($floorplanCategoryIds as $categoryId) {
                    if($count > 0){
                        $parent = Mage::getModel('catalog/category')->load($categoryId);
                        $title_2 .= ' | ' . $_helper->categoryAttribute($parent, $parent->getName(), 'name') . ' ' . $_helper->categoryAttribute($parent, $parent->getNameSuffix(), 'name_suffix');
                    }else {
                        $parent = Mage::getModel('catalog/category')->load($categoryId);
                        $title_1 .= $_helper->categoryAttribute($parent, $parent->getName(), 'name') . ' <span>' . $_helper->categoryAttribute($parent, $parent->getNameSuffix(), 'name_suffix') . '</span>  ';
                        $superParent = $parent->getParentCategory();
                    }
                    $count++;
                }
            }
        ?>
            <div class="page-title">
                <h1>
                    <span class="title_1"><?php echo $superParent->getName()." <span>".$superParent->getNameSuffix()."</span>"; ?></span>
                    <span class="title_2" style="font-weight: 100;"> <?php echo Mage::getSingleton('core/session')->getBoardTitle2(); ?></span>
                </h1>
            </div>
            <?php
                if(isset($lastProductId)):
                    $msg = $this->__('%s was added to your shopping cart.', Mage::helper('core')->escapeHtml($productAdded->getName()));
            ?>
                <ul class="messages"><li class="success-msg"><ul><li><span><?php echo $msg; ?></span></li></ul></li></ul>
            <?php
                endif;
            ?>
            <div class="no-display">
                <input type="hidden" name="product" value="<?php echo $_floorplan->getId() ?>" />
                <input type="hidden" name="related_product" id="related-products-field" value="" />
            </div>

            <div class="product-shop" style="display: none;">
                <div class="designer">
                    <?php
                    $_imgSize = 300;
                    Mage::log(Mage::helper('validoc_designer/image')->init($_designer, 'image'));
                    $_imageUrl = Mage::helper('validoc_designer/image')->init($_designer, 'image')->resize($_imgSize);
                    ?>
                    <img src="<?php echo $_imageUrl; ?>">
                </div>
                <div class="product-name">
                    <span class="h1"><?php echo $_designer->getName(); ?></span>
                </div>
                <div class="product-name">
                    <span class="h1"><?php echo $_floorplan->getName(); ?></span>
                </div>

                <div class="price-info">
                    <?php echo $this->getPriceHtml($_floorplan); ?>
                    <?php echo $this->getChildHtml('bundle_prices') ?>
                    <?php echo $this->getTierPriceHtml() ?>
                </div>

                <div class="extra-info">
                    <?php echo $this->getReviewsSummaryHtml($_floorplan, 'default', false)?>
                    <?php echo $this->getChildHtml('product_type_availability'); ?>
                </div>

                <?php echo $this->getChildHtml('alert_urls') ?>

                <?php if ($_floorplan->getShortDescription()):?>
                    <div class="short-description">
                        <div class="std"><?php echo nl2br($_floorplan->getDescription()); ?></div>
                    </div>
                <?php endif;?>

                <?php echo $this->getChildHtml('other');?>

            </div>
            
            <?php $roomBg = $this->getRoomBg(); ?>
            <div class="bg-box" <?php echo (($roomBg) ? 'style="background-image: url('.$roomBg->getUrl().');"' : ''); ?>>
                <div class="container-board">
                    <div class="product-img-box">
                        <?php echo $this->getChildHtml('media') ?>
                    </div>
                    <div class="product-name to-uppercase grid-container">
                        <h1><?php echo $board->getName(); ?></h1>
                    </div>
                </div>
            </div>
            <h4 class="slogan to-uppercase"><?php echo $_designer->getName() . ", " .$_designer->getFirmName() . " <span class='separator'>|</span> order your custom fabric & design kit"; ?><div class="line"></div></h4>

            <div class="grid12-6 description-floorplan" style="display: none;">
                <p><?php echo $_floorplan->getDescription(); ?><br><a href="#"><span class="more">More ></span></a></p>
            </div>
            <!-- designer list -->
            <div class="grid12-6 designers-list" style="display: none;">
                <div class="grid12-4 designer-img">
                    <?php
                    $_imgSize = 300;
                    Mage::log(Mage::helper('validoc_designer/image')->init($_designer, 'image'));
                    $_imageUrl = Mage::helper('validoc_designer/image')->init($_designer, 'image')->resize($_imgSize);
                    ?>
                    <img src="<?php echo $_imageUrl; ?>">
                </div>
                <div class="grid12-8 info">
                    <h4 class="Yesteryear title">Designer</h4>
                    <h5><?php echo $_designer->getName() ?> <br> gallupi dessign inc.</h5>
                    <a href="#" class="more">See more designs from <?php echo $_designer->getName() ?> ></a>
                </div>
                <div class="clearer"></div>
                <!-- get started -->
                <div class="grid12-4 started">
                    <img src="<?php echo $this->getSkinUrl('images'); ?>/started-img.png">
                </div>
                <div class="grid12-8 info">
                    <h4 class="Yesteryear">Get started</h4>
                    <h5>order your custom fabric & design kit</h5>
                    <a href="#" class="more">Learn more ></a>
                </div>
            </div>
            <div class="floorplan-featured-title grid-container">
                <h5><?php echo "Pieces Featured in this Floorplan"; ?></h5>
                <div class="grid12-4 add-quote-list">
                    <?php
                        $floorplanCost = $_floorplan->getApproximateCost();
                        if(!isset($floorplanCost))
                            $floorplanCost = 0;
                    ?>
                    <a href="<?php echo $this->getUrl('validoc_floorplan/addmultiple'); ?>">ADD ALL to MY QUOTE LIST</a>
                    <p><?php echo "(approximate cost: &#36;".$floorplanCost.")"; ?></p>
                </div>
            </div>
            <?php $counter = 0; ?>
            <?php $serializedGrid = $_floorplan->getSerializedGrid(); ?>
            <?php if(empty($serializedGrid)): ?>
            <div class="products-list grid-container">
                <!-- 8-4 per line -->
                <?php if(isset($firstRow)): ?>
                <div class="product-row 8-4-line">
                    <?php for($i = 0; $i < count($firstRow); $i++): ?>
                        <?php if($i == 0): ?>
                            <?php $counter++; ?>
                            <div class="grid12-8 on" id="<?php echo $firstRow[$i]->getEntityId(); ?>">
                                <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($firstRow[$i]->getSmallImage()); ?>">
                                <p class="image-name"><?php echo "# ".$counter." <span class='separator-name'>|</span> ".$firstRow[$i]->getName(); ?>
                                    <?php
                                        $_productId = $firstRow[$i]->getEntityId();
                                        $_product = Mage::getModel('catalog/product')->load($_productId);
                                        $_manufacturerName = $_product->getAttributeText('manufacturer');
                                        if(isset($_manufacturerName))
                                            echo " <span class='separator-name'>|</span> ".$_manufacturerName;
                                    ?>
                                </p>
                            </div>
                        <?php endif; ?>
                        <?php if($i == 1): ?>
                            <?php $counter++; ?>
                            <div class="grid12-4 two" id="<?php echo $firstRow[$i]->getEntityId(); ?>">
                                <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($firstRow[$i]->getSmallImage()); ?>" alt="">
                                <p class="image-name"><?php echo "# ".$counter." <span class='separator-name'>|</span> ".$firstRow[$i]->getName(); ?>
                                    <?php
                                        $_productId = $firstRow[$i]->getEntityId();
                                        $_product = Mage::getModel('catalog/product')->load($_productId);
                                        $_manufacturerName = $_product->getAttributeText('manufacturer');
                                        if(isset($_manufacturerName))
                                            echo " <span class='separator-name'>|</span> ".$_manufacturerName;
                                    ?>
                                </p>
                            </div>
                        <?php endif; ?>
                    <?php endfor; ?>
                </div>
                <?php endif; ?>

                <!-- 3 per line -->
                <?php if(isset($secondRow)): ?>
                <div class="product-row 3-line">
                    <?php for($i = 0; $i < count($secondRow); $i++): ?>
                        <?php if($i == 0): ?>
                            <?php $counter++; ?>
                            <div class="grid12-4 three" id="<?php echo $secondRow[$i]->getEntityId(); ?>">
                                <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($secondRow[$i]->getSmallImage()); ?>" alt="">
                                <p class="image-name"><?php echo "# ".$counter." <span class='separator-name'>|</span> ".$secondRow[$i]->getName(); ?>
                                    <?php
                                        $_productId = $secondRow[$i]->getEntityId();
                                        $_product = Mage::getModel('catalog/product')->load($_productId);
                                        $_manufacturerName = $_product->getAttributeText('manufacturer');
                                        if(isset($_manufacturerName))
                                            echo " <span class='separator-name'>|</span> ".$_manufacturerName;
                                    ?>
                                </p>
                            </div>
                        <?php endif; ?>
                        <?php if($i == 1): ?>
                            <?php $counter++; ?>
                            <div class="grid12-4 four" id="<?php echo $secondRow[$i]->getEntityId(); ?>">
                                <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($secondRow[$i]->getSmallImage()); ?>" alt="">
                                <p class="image-name"><?php echo "# ".$counter." <span class='separator-name'>|</span> ".$secondRow[$i]->getName(); ?>
                                    <?php
                                        $_productId = $secondRow[$i]->getEntityId();
                                        $_product = Mage::getModel('catalog/product')->load($_productId);
                                        $_manufacturerName = $_product->getAttributeText('manufacturer');
                                        if(isset($_manufacturerName))
                                            echo " <span class='separator-name'>|</span> ".$_manufacturerName;
                                    ?>
                                </p>
                            </div>
                        <?php endif; ?>
                        <?php if($i == 2): ?>
                            <?php $counter++; ?>
                            <div class="grid12-4 five" id="<?php echo $secondRow[$i]->getEntityId(); ?>">
                                <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($secondRow[$i]->getSmallImage()); ?>" alt="">
                                <p class="image-name"><?php echo "# ".$counter." <span class='separator-name'>|</span> ".$secondRow[$i]->getName(); ?>
                                    <?php
                                        $_productId = $secondRow[$i]->getEntityId();
                                        $_product = Mage::getModel('catalog/product')->load($_productId);
                                        $_manufacturerName = $_product->getAttributeText('manufacturer');
                                        if(isset($_manufacturerName))
                                            echo " <span class='separator-name'>|</span> ".$_manufacturerName;
                                    ?>
                                </p>
                            </div>
                        <?php endif; ?>
                    <?php endfor; ?>
                </div>
                <?php endif; ?>

                <!-- 3 per line -->
                <?php if(isset($thirdRow)): ?>
                <div class="product-row 3-line">
                    <?php for($i = 0; $i < count($thirdRow); $i ++): ?>
                        <?php if($i == 0): ?>
                            <?php $counter++; ?>
                            <div class="grid12-4 six" id="<?php echo $thirdRow[$i]->getEntityId(); ?>">
                                <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($thirdRow[$i]->getSmallImage()); ?>" alt="">
                                <p class="image-name"><?php echo "# ".$counter." <span class='separator-name'>|</span> ".$thirdRow[$i]->getName(); ?>
                                    <?php
                                        $_productId = $thirdRow[$i]->getEntityId();
                                        $_product = Mage::getModel('catalog/product')->load($_productId);
                                        $_manufacturerName = $_product->getAttributeText('manufacturer');
                                        if(isset($_manufacturerName))
                                            echo " <span class='separator-name'>|</span> ".$_manufacturerName;
                                    ?>
                                </p>
                            </div>
                        <?php endif; ?>
                        <?php if($i == 1): ?>
                            <?php $counter++; ?>
                            <div class="grid12-4 seven" id="<?php echo $thirdRow[$i]->getEntityId(); ?>">
                                <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($thirdRow[$i]->getSmallImage()); ?>" alt="">
                                <p class="image-name"><?php echo "# ".$counter." <span class='separator-name'>|</span> ".$thirdRow[$i]->getName(); ?>
                                    <?php
                                        $_productId = $thirdRow[$i]->getEntityId();
                                        $_product = Mage::getModel('catalog/product')->load($_productId);
                                        $_manufacturerName = $_product->getAttributeText('manufacturer');
                                        if(isset($_manufacturerName))
                                            echo " <span class='separator-name'>|</span> ".$_manufacturerName;
                                    ?>
                                </p>
                            </div>
                        <?php endif; ?>
                        <?php if($i == 2): ?>
                            <?php $counter++; ?>
                            <div class="grid12-4 eight" id="<?php echo $thirdRow[$i]->getEntityId(); ?>">
                                <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($thirdRow[$i]->getSmallImage()); ?>" alt="">
                                <p class="image-name"><?php echo "# ".$counter." <span class='separator-name'>|</span> ".$thirdRow[$i]->getName(); ?>
                                    <?php
                                        $_productId = $thirdRow[$i]->getEntityId();
                                        $_product = Mage::getModel('catalog/product')->load($_productId);
                                        $_manufacturerName = $_product->getAttributeText('manufacturer');
                                        if(isset($_manufacturerName))
                                            echo " <span class='separator-name'>|</span> ".$_manufacturerName;
                                    ?>
                                </p>
                            </div>
                        <?php endif; ?>
                    <?php endfor; ?>
                </div>
                <?php endif; ?>

                <!-- 4-8 per line -->
                <?php if(isset($fourthRow)): ?>
                <div class="product-row 4-8-line">
                    <?php for($i = 0; $i < count($fourthRow); $i++): ?>
                        <?php if($i == 0): ?>
                            <?php $counter++; ?>
                            <div class="grid12-4 nine big" id="<?php echo $fourthRow[$i]->getEntityId(); ?>">
                                <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($fourthRow[$i]->getSmallImage()); ?>">
                                <!-- <p class="image-name"><?php echo $fourthRow[$i]->getName(); ?></p> -->
                                <p class="image-name"><?php echo "# ".$counter." <span class='separator-name'>|</span> ".$fourthRow[$i]->getName(); ?>
                                    <?php
                                        $_productId = $fourthRow[$i]->getEntityId();
                                        $_product = Mage::getModel('catalog/product')->load($_productId);
                                        $_manufacturerName = $_product->getAttributeText('manufacturer');
                                        if(isset($_manufacturerName))
                                            echo " <span class='separator-name'>|</span> ".$_manufacturerName;
                                    ?>
                                </p>
                            </div>
                        <?php endif; ?>
                            <!-- <div class="grid12-8"> -->
                                <?php if($i == 1): ?>
                                    <?php $counter++; ?>
                                    <div class="ten" id="<?php echo $fourthRow[$i]->getEntityId(); ?>">
                                        <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($fourthRow[$i]->getSmallImage()); ?>">
                                        <p class="image-name"><?php echo "# ".$counter." <span class='separator-name'>|</span> ".$fourthRow[$i]->getName(); ?>
                                    <?php
                                        $_productId = $fourthRow[$i]->getEntityId();
                                        $_product = Mage::getModel('catalog/product')->load($_productId);
                                        $_manufacturerName = $_product->getAttributeText('manufacturer');
                                        if(isset($_manufacturerName))
                                            echo " <span class='separator-name'>|</span> ".$_manufacturerName;
                                    ?>
                                </p>
                                    </div>
                                <?php endif; ?>
                                <?php if($i == 2): ?>
                                    <?php $counter++; ?>
                                    <div class="grid12-6 eleven" id="<?php echo $fourthRow[$i]->getEntityId(); ?>">
                                        <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($fourthRow[$i]->getSmallImage()); ?>">
                                        <p class="image-name"><?php echo "# ".$counter." <span class='separator-name'>|</span> ".$fourthRow[$i]->getName(); ?>
                                    <?php
                                        $_productId = $fourthRow[$i]->getEntityId();
                                        $_product = Mage::getModel('catalog/product')->load($_productId);
                                        $_manufacturerName = $_product->getAttributeText('manufacturer');
                                        if(isset($_manufacturerName))
                                            echo " <span class='separator-name'>|</span> ".$_manufacturerName;
                                    ?>
                                </p>
                                    </div>
                                <?php endif; ?>
                                <?php if($i == 3): ?>
                                    <?php $counter++; ?>
                                    <div class="grid12-6 twelve" id="<?php echo $fourthRow[$i]->getEntityId(); ?>">
                                        <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($fourthRow[$i]->getSmallImage()); ?>">
                                        <p class="image-name"><?php echo "# ".$counter." <span class='separator-name'>|</span> ".$fourthRow[$i]->getName(); ?>
                                    <?php
                                        $_productId = $fourthRow[$i]->getEntityId();
                                        $_product = Mage::getModel('catalog/product')->load($_productId);
                                        $_manufacturerName = $_product->getAttributeText('manufacturer');
                                        if(isset($_manufacturerName))
                                            echo " <span class='separator-name'>|</span> ".$_manufacturerName;
                                    ?>
                                </p>
                                    </div>
                                <?php endif; ?>
                            <!-- </div> -->
                    <?php endfor; ?>
                </div>
                <?php endif; ?>
                <!-- 3 per line -->
                <?php if(isset($fiveRow)): ?>
                <div class="product-row 3-line">
                    <?php for($i = 0; $i < count($fiveRow); $i ++): ?>
                        <?php if($i == 0): ?>
                            <?php $counter++; ?>
                            <div class="grid12-4 thirteen" id="<?php echo $fiveRow[$i]->getEntityId(); ?>">
                                <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($fiveRow[$i]->getSmallImage()); ?>" alt="">
                                <p class="image-name"><?php echo "# ".$counter." <span class='separator-name'>|</span> ".$fiveRow[$i]->getName(); ?>
                                    <?php
                                        $_productId = $fiveRow[$i]->getEntityId();
                                        $_product = Mage::getModel('catalog/product')->load($_productId);
                                        $_manufacturerName = $_product->getAttributeText('manufacturer');
                                        if(isset($_manufacturerName))
                                            echo " <span class='separator-name'>|</span> ".$_manufacturerName;
                                    ?>
                                </p>
                            </div>
                        <?php endif; ?>
                        <?php if($i == 1): ?>
                            <?php $counter++; ?>
                            <div class="grid12-4 fourteen" id="<?php echo $fiveRow[$i]->getEntityId(); ?>">
                                <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($fiveRow[$i]->getSmallImage()); ?>" alt="">
                                <p class="image-name"><?php echo "# ".$counter." <span class='separator-name'>|</span> ".$fiveRow[$i]->getName(); ?>
                                    <?php
                                        $_productId = $fiveRow[$i]->getEntityId();
                                        $_product = Mage::getModel('catalog/product')->load($_productId);
                                        $_manufacturerName = $_product->getAttributeText('manufacturer');
                                        if(isset($_manufacturerName))
                                            echo " <span class='separator-name'>|</span> ".$_manufacturerName;
                                    ?>
                                </p>
                            </div>
                        <?php endif; ?>
                        <?php if($i == 2): ?>
                            <?php $counter++; ?>
                            <div class="grid12-4 fifteen" id="<?php echo $fiveRow[$i]->getEntityId(); ?>">
                                <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($fiveRow[$i]->getSmallImage()); ?>" alt="">
                                <p class="image-name"><?php echo "# ".$counter." <span class='separator-name'>|</span> ".$fiveRow[$i]->getName(); ?>
                                    <?php
                                        $_productId = $fiveRow[$i]->getEntityId();
                                        $_product = Mage::getModel('catalog/product')->load($_productId);
                                        $_manufacturerName = $_product->getAttributeText('manufacturer');
                                        if(isset($_manufacturerName))
                                            echo " <span class='separator-name'>|</span> ".$_manufacturerName;
                                    ?>
                                </p>
                            </div>
                        <?php endif; ?>
                    <?php endfor; ?>
                </div>
                <?php endif; ?>
                <!-- 8-4 per line -->
                <?php if(isset($sixRow)): ?>
                <div class="product-row 8-4-line estito">
                    <?php for($i = 0; $i < count($sixRow); $i++): ?>
                        <?php if($i == 0): ?>
                            <?php $counter++; ?>
                            <div class="grid12-8 sixteen" id="<?php echo $sixRow[$i]->getEntityId(); ?>">
                                <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($sixRow[$i]->getSmallImage()); ?>" alt="">
                                <p class="image-name"><?php echo "# ".$counter." <span class='separator-name'>|</span> ".$sixRow[$i]->getName(); ?>
                                    <?php
                                        $_productId = $sixRow[$i]->getEntityId();
                                        $_product = Mage::getModel('catalog/product')->load($_productId);
                                        $_manufacturerName = $_product->getAttributeText('manufacturer');
                                        if(isset($_manufacturerName))
                                            echo " <span class='separator-name'>|</span> ".$_manufacturerName;
                                    ?>
                                </p>
                            </div>
                        <?php endif; ?>
                        <?php if($i == 1): ?>
                            <?php $counter++; ?>
                            <div class="grid12-4 seventeen" id="<?php echo $sixRow[$i]->getEntityId(); ?>">
                                <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($sixRow[$i]->getSmallImage()); ?>" alt="">
                                <p class="image-name"><?php echo "# ".$counter." <span class='separator-name'>|</span> ".$sixRow[$i]->getName(); ?>
                                    <?php
                                        $_productId = $sixRow[$i]->getEntityId();
                                        $_product = Mage::getModel('catalog/product')->load($_productId);
                                        $_manufacturerName = $_product->getAttributeText('manufacturer');
                                        if(isset($_manufacturerName))
                                            echo " <span class='separator-name'>|</span> ".$_manufacturerName;
                                    ?>
                                </p>
                            </div>
                        <?php endif; ?>
                    <?php endfor; ?>
                </div>
                <?php endif; ?>
                <!-- 8-4 per line -->
                <?php if(isset($sevenRow)): ?>
                <div class="product-row 8-4-line">
                    <?php for($i = 0; $i < count($sevenRow); $i++): ?>
                    <!-- <div class="grid12-8"> -->
                        <?php if($i == 0): ?>
                            <?php $counter++; ?>
                            <div class="grid12-6 nineteen" id="<?php echo $sevenRow[$i]->getEntityId(); ?>">
                                <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($sevenRow[$i]->getSmallImage()); ?>">
                                <p class="image-name"><?php echo "# ".$counter." <span class='separator-name'>|</span> ".$sevenRow[$i]->getName(); ?>
                                    <?php
                                        $_productId = $sevenRow[$i]->getEntityId();
                                        $_product = Mage::getModel('catalog/product')->load($_productId);
                                        $_manufacturerName = $_product->getAttributeText('manufacturer');
                                        if(isset($_manufacturerName))
                                            echo " <span class='separator-name'>|</span> ".$_manufacturerName;
                                    ?>
                                </p>
                            </div>
                        <?php endif; ?>
                        <?php if($i == 1): ?>
                            <?php $counter++; ?>
                            <div class="grid12-6 twenty" id="<?php echo $sevenRow[$i]->getEntityId(); ?>">
                                <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($sevenRow[$i]->getSmallImage()); ?>">
                                <p class="image-name"><?php echo "# ".$counter." <span class='separator-name'>|</span> ".$sevenRow[$i]->getName(); ?>
                                    <?php
                                        $_productId = $sevenRow[$i]->getEntityId();
                                        $_product = Mage::getModel('catalog/product')->load($_productId);
                                        $_manufacturerName = $_product->getAttributeText('manufacturer');
                                        if(isset($_manufacturerName))
                                            echo " <span class='separator-name'>|</span> ".$_manufacturerName;
                                    ?>
                                </p>
                            </div>
                        <?php endif; ?>
                        <?php if($i == 2): ?>
                            <?php $counter++; ?>
                            <div class="eighteen" id="<?php echo $sevenRow[$i]->getEntityId(); ?>">
                                <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($sevenRow[$i]->getSmallImage()); ?>">
                                <p class="image-name"><?php echo "# ".$counter." <span class='separator-name'>|</span> ".$sevenRow[$i]->getName(); ?>
                                    <?php
                                        $_productId = $sevenRow[$i]->getEntityId();
                                        $_product = Mage::getModel('catalog/product')->load($_productId);
                                        $_manufacturerName = $_product->getAttributeText('manufacturer');
                                        if(isset($_manufacturerName))
                                            echo " <span class='separator-name'>|</span> ".$_manufacturerName;
                                    ?>
                                </p>
                            </div>
                        <?php endif; ?>
                    <!-- </div> -->
                    <?php if($i == 3): ?>
                        <?php $counter++; ?>
                        <div class="grid12-4 twenty-one big" id="<?php echo $sevenRow[$i]->getEntityId(); ?>">
                            <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($sevenRow[$i]->getSmallImage()); ?>">
                            <p class="image-name"><?php echo "# ".$counter." <span class='separator-name'>|</span> ".$sevenRow[$i]->getName(); ?>
                                <?php
                                    $_productId = $sevenRow[$i]->getEntityId();
                                    $_product = Mage::getModel('catalog/product')->load($_productId);
                                    $_manufacturerName = $_product->getAttributeText('manufacturer');
                                    if(isset($_manufacturerName))
                                        echo " <span class='separator-name'>|</span> ".$_manufacturerName;
                                ?>
                            </p>
                        </div>
                    <?php endif; ?>
                    <?php endfor; ?>
                </div>
                <?php endif; ?>
                <!-- 4-8 per line -->
                <?php if(isset($eightRow)): ?>
                <div class="product-row 4-8-line">
                <?php for($i = 0; $i < count($eightRow); $i++): ?>
                    <?php if($i == 0): ?>
                        <?php $counter++; ?>
                        <div class="grid12-4 twenty-two" id="<?php echo $eightRow[$i]->getEntityId(); ?>">
                            <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($eightRow[$i]->getSmallImage()); ?>" alt="">
                            <p class="image-name"><?php echo "# ".$counter." <span class='separator-name'>|</span> ".$eightRow[$i]->getName(); ?>
                                <?php
                                    $_productId = $eightRow[$i]->getEntityId();
                                    $_product = Mage::getModel('catalog/product')->load($_productId);
                                    $_manufacturerName = $_product->getAttributeText('manufacturer');
                                    if(isset($_manufacturerName))
                                        echo " <span class='separator-name'>|</span> ".$_manufacturerName;
                                ?>
                            </p>
                        </div>
                    <?php endif; ?>
                    <?php if($i == 1): ?>
                        <?php $counter++; ?>
                        <div class="grid12-8 twenty-three" id="<?php echo $eightRow[$i]->getEntityId(); ?>">
                            <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($eightRow[$i]->getSmallImage()); ?>" alt="">
                            <p class="image-name"><?php echo "# ".$counter." <span class='separator-name'>|</span> ".$eightRow[$i]->getName(); ?>
                                <?php
                                    $_productId = $eightRow[$i]->getEntityId();
                                    $_product = Mage::getModel('catalog/product')->load($_productId);
                                    $_manufacturerName = $_product->getAttributeText('manufacturer');
                                    if(isset($_manufacturerName))
                                        echo " <span class='separator-name'>|</span> ".$_manufacturerName;
                                ?>
                            </p>
                        </div>
                    <?php endif; ?>
                    <?php endfor; ?>
                </div>
                <?php endif; ?>
                <!-- 8-4 per line -->
                <?php if(isset($nineRow)): ?>
                <div class="product-row 8-4-line">
                <?php for($i = 0; $i < count($nineRow); $i++): ?>
                    <!-- <div class="grid12-8"> -->
                        <?php if($i == 0): ?>
                            <?php $counter++; ?>
                            <div class="twenty-four" id="<?php echo $nineRow[$i]->getEntityId(); ?>">
                                <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($nineRow[$i]->getSmallImage()); ?>">
                                <p class="image-name"><?php echo "# ".$counter." <span class='separator-name'>|</span> ".$nineRow[$i]->getName(); ?>
                                    <?php
                                        $_productId = $nineRow[$i]->getEntityId();
                                        $_product = Mage::getModel('catalog/product')->load($_productId);
                                        $_manufacturerName = $_product->getAttributeText('manufacturer');
                                        if(isset($_manufacturerName))
                                            echo " <span class='separator-name'>|</span> ".$_manufacturerName;
                                    ?>
                                </p>
                            </div>
                        <?php endif; ?>
                        <?php if($i == 1): ?>
                            <?php $counter++; ?>
                            <div class="grid12-6 twenty-five" id="<?php echo $nineRow[$i]->getEntityId(); ?>">
                                <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($nineRow[$i]->getSmallImage()); ?>">
                                <p class="image-name"><?php echo "# ".$counter." <span class='separator-name'>|</span> ".$nineRow[$i]->getName(); ?>
                                    <?php
                                        $_productId = $nineRow[$i]->getEntityId();
                                        $_product = Mage::getModel('catalog/product')->load($_productId);
                                        $_manufacturerName = $_product->getAttributeText('manufacturer');
                                        if(isset($_manufacturerName))
                                            echo " <span class='separator-name'>|</span> ".$_manufacturerName;
                                    ?>
                                </p>
                            </div>
                        <?php endif; ?>
                        <?php if($i == 2): ?>
                            <?php $counter++; ?>
                            <div class="grid12-6 twenty-six" id="<?php echo $nineRow[$i]->getEntityId(); ?>">
                                <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($nineRow[$i]->getSmallImage()); ?>">
                                <p class="image-name"><?php echo "# ".$counter." <span class='separator-name'>|</span> ".$nineRow[$i]->getName(); ?>
                                    <?php
                                        $_productId = $nineRow[$i]->getEntityId();
                                        $_product = Mage::getModel('catalog/product')->load($_productId);
                                        $_manufacturerName = $_product->getAttributeText('manufacturer');
                                        if(isset($_manufacturerName))
                                            echo " <span class='separator-name'>|</span> ".$_manufacturerName;
                                    ?>
                                </p>
                            </div>
                        <?php endif; ?>
                    <!-- </div> -->
                    <?php if($i == 3): ?>
                        <?php $counter++; ?>
                        <div class="grid12-4 twenty-seven big" id="<?php echo $nineRow[$i]->getEntityId(); ?>">
                            <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($nineRow[$i]->getSmallImage()); ?>">
                            <p class="image-name"><?php echo "# ".$counter." <span class='separator-name'>|</span> ".$nineRow[$i]->getName(); ?>
                                <?php
                                    $_productId = $nineRow[$i]->getEntityId();
                                    $_product = Mage::getModel('catalog/product')->load($_productId);
                                    $_manufacturerName = $_product->getAttributeText('manufacturer');
                                    if(isset($_manufacturerName))
                                        echo " <span class='separator-name'>|</span> ".$_manufacturerName;
                                ?>
                            </p>
                        </div>
                    <?php endif; ?>
                <?php endfor; ?>
                </div>
                <?php endif; ?>
                <!-- 3 per line -->
                <?php if(isset($tenRow)): ?>
                <div class="product-row 3-line">
                <?php for($i = 0; $i < count($tenRow); $i++): ?>
                    <?php if($i == 0): ?>
                        <?php $counter++; ?>
                        <div class="grid12-4 twenty-eight" id="<?php echo $tenRow[$i]->getEntityId(); ?>">
                            <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($tenRow[$i]->getSmallImage()); ?>" alt="">
                            <p class="image-name"><?php echo "# ".$counter." <span class='separator-name'>|</span> ".$tenRow[$i]->getName(); ?>
                                <?php
                                    $_productId = $tenRow[$i]->getEntityId();
                                    $_product = Mage::getModel('catalog/product')->load($_productId);
                                    $_manufacturerName = $_product->getAttributeText('manufacturer');
                                    if(isset($_manufacturerName))
                                        echo " <span class='separator-name'>|</span> ".$_manufacturerName;
                                ?>
                            </p>
                        </div>
                    <?php endif; ?>
                    <?php if($i == 1): ?>
                        <?php $counter++; ?>
                        <div class="grid12-4 twenty-nine" id="<?php echo $tenRow[$i]->getEntityId(); ?>">
                            <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($tenRow[$i]->getSmallImage()); ?>" alt="">
                            <p class="image-name"><?php echo "# ".$counter." <span class='separator-name'>|</span> ".$tenRow[$i]->getName(); ?>
                                <?php
                                    $_productId = $tenRow[$i]->getEntityId();
                                    $_product = Mage::getModel('catalog/product')->load($_productId);
                                    $_manufacturerName = $_product->getAttributeText('manufacturer');
                                    if(isset($_manufacturerName))
                                        echo " <span class='separator-name'>|</span> ".$_manufacturerName;
                                ?>
                            </p>
                        </div>
                    <?php endif; ?>
                    <?php if($i == 2): ?>
                        <?php $counter++; ?>
                        <div class="grid12-4 thirty" id="<?php echo $tenRow[$i]->getEntityId(); ?>">
                            <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($tenRow[$i]->getSmallImage()); ?>" alt="">
                            <p class="image-name"><?php echo "# ".$counter." <span class='separator-name'>|</span> ".$tenRow[$i]->getName(); ?>
                                <?php
                                    $_productId = $tenRow[$i]->getEntityId();
                                    $_product = Mage::getModel('catalog/product')->load($_productId);
                                    $_manufacturerName = $_product->getAttributeText('manufacturer');
                                    if(isset($_manufacturerName))
                                        echo " <span class='separator-name'>|</span> ".$_manufacturerName;
                                ?>
                            </p>
                        </div>
                    <?php endif; ?>
                    <?php endfor; ?>
                </div>
                <?php endif; ?>
                <?php
                    $k = 30;
                    $extraCounter = 31;
                    while(array_key_exists($k, $indexes)):
                        $genericRow = array_slice($productsFloorplan, $k, 3);
                ?>
                    <?php //var_dump($genericRow); ?>
                        <div class="product-row 3-line extra">
                            <?php for($j = 0; $j < count($genericRow); $j++): ?>
                            <div class="grid12-4" id="<?php echo $genericRow[$j]->getEntityId(); ?>">
                                <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($genericRow[$j]->getSmallImage()); ?>" alt="">
                                <p class="image-name">
                                    <?php echo "# ".$extraCounter." <span class='separator-name'>|</span> ".$genericRow[$j]->getName(); ?>
                                    <?php
                                        $_productId = $genericRow[$j]->getEntityId();
                                        $_product = Mage::getModel('catalog/product')->load($_productId);
                                        $_manufacturerName = $_product->getAttributeText('manufacturer');
                                        if(isset($_manufacturerName))
                                            echo " <span class='separator-name'>|</span> ".$_manufacturerName;
                                    ?>
                                </p>
                            </div>
                            <?php $extraCounter++; ?>
                        <?php endfor; ?>
                        </div>
                <?php
                    $k = $k + 3;
                    endwhile;
                ?>
                <div class="floorplan-featured-title grid-container bottom">
                    <div class="grid12-4 add-quote-list">
                        <a href="#">ADD ALL to MY QUOTE LIST</a>
                        <p><?php echo "(approximate cost: &#36;".$floorplanCost.")"; ?></p>
                    </div>
                </div>
            </div><!-- product list -->
            <?php else://there is grid customization ?>
                <?php
                    $savedGrid = $_floorplan->getSerializedGrid();
                    $savedGrid = json_decode($savedGrid, true);
                    $savedGrid = json_decode($savedGrid, true);
                ?>
                    <div class="products-list grid-container gridster">
                        <div class="inner">
                            <?php foreach($savedGrid as $cell): ?>
                                <div id="<?php echo $cell['id']; ?>" data-row="<?php echo $cell['row']; ?>" data-col="<?php echo $cell['col']; ?>" data-sizex="<?php echo $cell['size_x']; ?>" data-sizey="<?php echo $cell['size_y']; ?>">
                                    <?php foreach($productsFloorplan as $item): ?>
                                        <?php if($cell['id'] == $item->getEntityId()): ?>
                                            <?php
                                                $gridImg = Mage::getModel('catalog/product')->load($item->getEntityId())->getMediaGalleryImages()->getItemByColumnValue('label', 'grid');
                                                if(!isset($gridImg)){
                                                    $pImage = $item->getSmallImage();
                                                }else{
                                                    $pImage = $gridImg['file'];
                                                }
                                            ?>
                                            <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl($pImage); ?>">
                                            <?php $counter++; ?>
                                            <p class="image-name">
                                                <?php //echo $item->getName();//only name ?>
                                                <?php
                                                    //getting number product
                                                    $floorplanId  = (int) $this->getRequest()->getParam('id');
                                                    $number = $this->getProductNumber($floorplanId, $cell['id']);
                                                    echo '#'.$number[0]['position']." <span class='separator-name'>|</span> ";
                                                    $_product = Mage::getModel('catalog/product')->load($item->getEntityId());
                                                        $manufacturerPiece = $_product->getAttributeText('manufacturer_pieces');
                                                        if(isset($manufacturerPiece))
                                                            echo $manufacturerPiece;
                                                ?>
                                                <?php
                                                    //manufacturer name
                                                    $_productId = $item->getEntityId();
                                                    $_product = Mage::getModel('catalog/product')->load($_productId);
                                                    $_manufacturerName = $_product->getAttributeText('manufacturer');
                                                    if(isset($_manufacturerName) && $_manufacturerName != false)
                                                        echo " <span class='separator-name'>|</span> ".$_manufacturerName;
                                                ?>
                                            </p>
                                        <?php endif; ?>
                                    <?php endforeach; ?>
                                </div>
                            <?php endforeach; ?>
                        </div>
                        <div class="floorplan-featured-title grid-container bottom">
                            <div class="grid12-4 add-quote-list">
                                <a href="#">ADD ALL to MY QUOTE LIST</a>
                                <p><?php echo "(approximate cost: &#36;".$floorplanCost.")"; ?></p>
                            </div>
                        </div>
                    </div>
            <?php endif; ?>
            <?php foreach($productsFloorplan as $key => $_product): ?>
                 <div class="container popup floorplan" id="popup-<?php echo $_product->getEntityId(); ?>" style="display: none;">
                    <?php
                        $mainImg = null;
                        $images = Mage::getModel('catalog/product')->load($_product->getEntityId())->getMediaGalleryImages();
                        foreach ($images as $img) {
                            if($img['label'] == 'popup'){
                                $mainImg = $img;
                            }
                        }
                        //var_dump($mainImg);
                    ?>
                    <div class="grid12-6 popup-images">
                        <div class="main-img">
                            <?php if($mainImg): ?>
                                <img src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail', $mainImg['file']); ?>">
                            <?php else: ?>
                                <img src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail', $_product->getImage()); ?>" alt="">
                            <?php endif; ?>
                        </div>
                        <div class="extra-imgs">
                            <ul>
                                <?php foreach($images as $img): ?>
                                    <?php if($img['label'] == 'popup'): ?>
                                        <li>
                                            <img src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail', $img['file']); ?>" alt="">
                                        </li>
                                    <?php endif; ?>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                    </div>
                    <div class="grid12-6 popup-info">
                        <h2><?php echo $_product->getName(); ?></h2>
                        <p>featured in <span>
                            <?php
                                $prod = Mage::getModel('catalog/product')->load($_product->getEntityId());
                                $rooms = $prod->getBoardId();
                                if(!empty($rooms)){
                                    $roomIds = explode(",", $rooms);
                                    $boardsCollection = array();
                                    foreach ($roomIds as $key => $roomId) {
                                        $board = Mage::getModel('validoc_board/board')->load($roomId);
                                        array_push($boardsCollection, $board);
                                    }
                                }
                                foreach ($boardsCollection as $key => $board) {
                                    echo '<a class="popup-link" href="'.Mage::getBaseUrl().'designer-board/board/view/id/'.$board->getBoardId().'">'.$board->getName();
                                    if($key != count($boardsCollection)-1){
                                        echo "</a>, ";
                                    }else{
                                        echo "</a>";
                                    }
                                }
                                $firstBoard = $boardsCollection[0];
                            ?>
                        </span></p>
                        <p class="description"><?php echo $_product->getShortDescription(); ?></p>
                        <p class="description dimensions"><?php echo $_product->getDimensions(); ?></p>
                        <p class="description arrival" style="display: none;">ESTIMATED ARRIVAL: <?php echo $_product->getEstimatedArrival(); ?></p>
                        <p class="description upon">PRICE UPON REQUEST</p>
                        <div class="actions clearer<?php echo $actionsClasses; ?> shop">
                                <?php //Cart button ?>
                                    <?php if ($_product->isSaleable()): ?>
                                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->helper('checkout/cart')->getAddUrl($_product) ?>')"><span><span><?php echo $this->__('add to my quote list') ?></span></span></button>
                                    <?php else: ?>
                                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                    <?php endif; ?>
                            </div>
                    </div>
                 </div>
            <?php endforeach; ?>



            <?php echo $this->getChildHtml('related_products') ?>

            <?php echo $this->getChildHtml('floorplan_related_products') ?>
            <div class="clearer"></div>
        </form>
    </div>



    <?php echo $this->getChildHtml('upsell_products') ?>
    <?php echo $this->getChildHtml('product_additional_data') ?>

</div>
<?php
    //link to most recent visited page
    $currentUrl = Mage::helper('core/url')->getCurrentUrl();
    $session = Mage::getSingleton("core/session", array('name' => 'frontend'));
    $session->setData("last_visited_page", $currentUrl);
?>

<script type="text/javascript">
    jQuery(document).ready(function(){
        //slider
        var flagString = new RegExp("[Ff]loorplan");
        jQuery('.product-image-thumbs li a').each(function(){
            var stringView = jQuery(this).find('h4').text()
                if(flagString.test(stringView)){
                    jQuery(this).addClass('floorplan');
                }
            });

        var bannerImg = jQuery('.product-image-gallery img');
        /*jQuery('.product-image-thumbs li a:not(.floorplan)').click(function(){
            var src = jQuery(this).find('img').attr('src');
            bannerImg.attr('src', src);
            var currentImg = jQuery(this).find('img').attr('class');
            bannerImg.attr('src', src);
            //session storage
            if(window.sessionStorage){
                sessionStorage.setItem('floorplan-img', currentImg);
            }
            jQuery('.product-image-thumbs li').removeClass('active');
            jQuery(this).parent().addClass('active');

            return false;
        });*/
        //for selecting image in boards page
        jQuery('.product-image-thumbs li a:not(.floorplan)').click(function(){
            var src = jQuery(this).find('img').attr('src');
            if(window.sessionStorage){
                sessionStorage.setItem('selected-floorplan-img', src);
            }
        });
        //wrap
        jQuery('.ten, .eleven, .twelve').wrapAll("<div class='grid12-8'></div>");
        jQuery('.eighteen, .nineteen, .twenty').wrapAll("<div class='grid12-8'></div>");
        jQuery('.twenty-four, .twenty-five, .twenty-six').wrapAll("<div class='grid12-8'></div>");
        //equalizer
        jQuery('.product-row div:not(.big)').equalizer({
            min: 226,
            max: 226,
            columns: '> img',
        });
        jQuery('.product-row div.big').equalizer({
            min: 603,
            max: 603,
            columns: '> img',
        });
        <?php $serializedGrid = $_floorplan->getSerializedGrid(); ?>
        <?php if(!empty($serializedGrid)): ?>
            var gridster = jQuery('.products-list .inner').gridster({
                max_cols: 3,
                widget_margins: [20, 60],
                widget_base_dimensions: [300, 300],
                widget_selector: "div",
                resize: {
                    enabled: false
                }
            }).data('gridster');
            gridster.disable();
        <?php endif; ?>
        //add all to my quote button
        var addMultipleUrl = '<?php echo $this->getUrl("validoc_floorplan/floorplan/addmultiple") ?>';
        var floorplanProducts = '<?php echo json_encode($_floorplan_products); ?>';
        json_data = {products_requested: floorplanProducts};
        var cartUrl = '<?php echo Mage::helper("checkout/cart")->getCartUrl(); ?>';

        jQuery('.add-quote-list').click(function(){
            //console.log(json_data);
            new Ajax.Request(addMultipleUrl, {
                method: 'post',
                parameters: json_data,
                requestHeaders: {Accept: 'application/json'},
                onSuccess: function(transport){
                    json = transport.responseText.evalJSON();
                    console.log(json);
                    window.location.href = cartUrl;
                }
            });
            return false;
        });
        jQuery('.floorplans-title, .rooms-floorplans').hover(function(){
            jQuery('.floorplans-title').css({
                'color': '#000',
                'font-weight': '500'
            });
        }, function(){
            jQuery('.floorplans-title').removeAttr('style');
        });
        //width of bg-box handler
        mainContainerWidth = jQuery('.validoc-floorplan-floorplan-view .main-container').width();
        console.log(mainContainerWidth);
        bgLeft = jQuery('.validoc-floorplan-floorplan-view .show-bg').css('margin-left');
        bgLeft = parseInt(bgLeft) + 13;
        jQuery('.bg-box').css({
            'margin-left': '-' + bgLeft + 'px',
            'margin-right': '-' + bgLeft + 'px'
        });

        //popup behavior
        jQuery('.grid-container .inner > div, .grid-container .product-row > div').on('click',  function(){
            var target = jQuery(this).attr('id');
            jQuery('.page-title.category-title h1 span.title_1').css('z-index', 'auto');
            jQuery('.logo.logo--regular, #nav, .footer-container').css('z-index', '9');
            jQuery('.grid-container .inner > div, .grid-container .product-row > div').fancybox({
                href: '#popup-' + target,
                titleShow: false,
                transitionIn: 'elastic',
                transitionOut: 'elastic',
                autoscale: true,
                scrolling: 'no',
                maxWidth: 800,
                maxHeight: 550,
                width: '100%',
                height: 550,
                autoSize: false,
                afterClose: function(){
                    jQuery('.logo.logo--regular, #nav, .footer-container, .sticky-container, .footer-container').removeAttr('style');
                    jQuery('.page-title.category-title h1 span.title_1').removeAttr('style');
                    jQuery('.container-board .product-name.to-uppercase.grid-container').css('z-index', '100');
                },
                beforeShow: function(){
                    jQuery('#nav, .sticky-container, .footer-container').css('z-index', '5');
                    jQuery('.logo.logo--regular').css('z-index', '6');
                    jQuery('.container-board .product-name.to-uppercase.grid-container').css('z-index', 'auto');
                }
            });
            //change imgs
            jQuery('.extra-imgs ul li img').click(function(){
                var mainParentContainer = jQuery(this).parent().parent().parent().parent().parent();
                mainParentContainer.find('.main-img').find('img').attr('src', jQuery(this).attr('src'));
            });
        });
        //setting time to magento messages
        if(jQuery('.messages').length > 0){
            jQuery('.messages').delay(6000).slideUp(500);
        }
    });
</script>