<?php

/* @var $this Validoc_Fabric_Block_Detail_View_Media */
?>
<?php $_fabric = $this->getFabric(); ?>
<div class="product-image product-image-zoom">
    <div class="product-image-gallery">
        <?php
        $_imgSize = 472;
        $_imageUrl = Mage::helper('validoc_fabric/image')->init($_fabric, 'image')->resize($_imgSize);
        ?>
        <?php
        //$_imageUrl = Mage::helper('validoc_fabric/image')->init($_fabric, 'image');
        ?>
        <img id="image-main" class="gallery-image visible" src="<?php echo $_imageUrl; ?>">
        <!--<?php
        /*$i=0;
        foreach ($this->getGalleryImages() as $_image):
            $_imageUrl = $this->helper('validoc_fabric/image')
                ->init($_fabric, 'image', $_image->getFile())
                ->keepFrame(false)
                ->constrainOnly(true)
                ->resize(1200);
            ?>
            <img id="image-<?php echo $i; ?>"
                 class="gallery-image"
                 src="<?php echo $_imageUrl; ?>"
                 data-zoom-image="<?php echo $_imageUrl; ?>" />
            <?php
            $i++;
        endforeach;*/
        ?>-->
    </div>
</div>

<?php if (count($this->getGalleryImages()) > 0): ?>
    <div class="more-views">
        <!--<h2><?php //echo $this->__('More Views') ?></h2>-->
        <ul class="product-image-thumbs">
            <?php $i=0; foreach ($this->getGalleryImages() as $_image): ?>
                <li>
                    <a class="thumb-link" href="#" title="<?php echo $this->escapeHtml($_image->getLabel()) ?>" data-image-index="<?php echo $i; ?>">
                        <img src="<?php echo $this->helper('validoc_fabric/image')->init($this->getFabric(), 'thumbnail', $_image->getFile())->resize(75); ?>"
                             width="75" height="75" alt="<?php echo $this->escapeHtml($_image->getLabel()) ?>" />
                    </a>
                </li>
                <?php $i++; endforeach; ?>
        </ul>
    </div>
<?php endif; ?>

<?php echo $this->getChildHtml('after'); ?>
