<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>

<?php $post = $this->getPost() ?>
<div class="post-list-item">
	<?php echo $this->getBeforePostContentHtml() ?>
	<div class="post-entry entry<?php if ($post->getFeaturedImage()): ?> post-entry-with-image<?php endif; ?>">
		<?php if ($post->isViewableForVisitor()): ?>

			<div class="float_left">
				<?php if ($featuredImage = $post->getFeaturedImage()): ?>

					<?php							
					$img_src=  Mage::getBaseUrl()."/timthumb.php?src=".$featuredImage->getFullSizeImage()."&w=300&h=173";
					
					$handle = @fopen($img_src,'r');
					if($handle !== false)							
					{?>
					<div class="blog_featured_image_container featured-image left">
						<a href="<?php echo $post->getPermalink() ?>" title="<?php echo $this->escapeHtml($post->getPostTitle()) ?>">							
							<!-- <img class="blog_featured_image" src="<?php echo $featuredImage->getFullSizeImage() ?>" alt="<?php echo $this->escapeHtml($post->getPostTitle()) ?>"/> -->							
								<img class="blog_featured_image" 
									  src="<?php echo $img_src?>"
									  alt="<?php echo $this->escapeHtml($post->getPostTitle()) ?>"/>						  	
						</a>
					</div>
					<?php
				   }
				  	?>
				<?php endif; ?>
			</div>

				<h2 class="post_title">
					<a href="<?php echo $post->getPermalink() ?>" title="<?php echo $this->escapeHtml($post->getPostTitle()) ?>">
						<?php echo $this->escapeHtml($post->getPostTitle()) ?>
					</a>
				</h2>
				
				<!-- <div class="design-text"> -->
				<div class="text_style">
				<?php
				ob_start();
				?>
					<?php if ($this->displayExcerptInFeed() || $post->hasMoreTag()): ?>
						<?php echo $post->getPostExcerpt() ?>
					<?php else: ?>
						<?php echo $post->getPostContent() ?>
					<?php endif; ?>			
				<?php
				$str_text = ob_get_clean();
				echo substr(strip_tags($str_text), 0, 170);
				?>
				</div>

				<div class="blog_read_more">
					<a href="<?php echo $post->getPermalink()?>">
						Read More &raquo;
					</a>
				</div>
			

		<?php else: ?>
			<?php echo $this->getPasswordProtectHtml($post) ?>
		<?php endif; ?>
	</div>
	<?php //echo $this->getAfterPostContentHtml() ?>
</div>