<?php

/* @var $this Validoc_Board_Block_Detail_View_Media */
?>
<?php
$_board = $this->getBoard();
$mainImage = $this->getMainImage();//var_dump($mainImage);die('die here');
?>
<div class="product-image product-image-zoom grid12-10">
    <div class="product-image-gallery">
        <?php if(!empty($mainImage)): ?>
          <div class="inspiration-buttons" style="display:none">
            <div class="inspiration-prev"></div>
            <div class="inspiration-next"></div>
          </div>
          <img id="image-main"
               class="gallery-image visible"
               src="<?php echo $this->helper('validoc_board/image')->init($this->getBoard(), 'thumbnail', $mainImage->getFile()); ?>"
               alt="<?php echo $this->escapeHtml($this->getImageLabel()) ?>"
               title="<?php echo $this->escapeHtml($this->getImageLabel()); ?>" />
        <?php else: ?>
          <div class="empty" style="border: 2px solid #000;box-shadow: 0 0 20px #555;min-height: 400px;position: relative;"><p style="position: absolute;top: 46%; left: 31.5%;font-size: 2em;text-shadow: 1px 1px 5px #777;">There is no images assigned</p></div>
        <?php endif; ?>

        <?php
        if(false):
        $i=0;
        foreach ($this->getGalleryImages() as $_image):
            $_imageUrl = $this->helper('validoc_board/image')
                ->init($_board, 'image', $_image->getFile())
                ->keepFrame(false)
                ->constrainOnly(true)
                ->resize(1200);
            ?>
            <img id="image-<?php echo $i; ?>"
                 class="gallery-image"
                 src="<?php echo $_imageUrl; ?>"
                 data-zoom-image="<?php echo  $_imageUrl; ?>" />
            <?php
            $i++;
        endforeach;
        endif;
        ?>
    </div>
</div>

<?php 
$m = Mage::getModel("validoc_board/board");
$floorplans = $m->getFloorplans($this->getBoard()->getId());
if (count($this->getGalleryImages()) > 0 || !empty($floorplans)): ?>
    <div class="more-views grid12-2">
        <h2><img src="<?php echo $this->getSkinUrl('images/view-title.png'); ?>"></h2>
        <ul class="product-image-thumbs">
          <?php $inspirationCounter = 0; ?>
            <?php $i=0; foreach ($this->getGalleryImages() as $_image): ?>
              <?php
                $label = $_image->getLabel();
                $label = strtolower(trim($label));
                if($label == 'inspiration'){
                  $inspirationCounter++;
                }
                if( ($label == 'background') || (($inspirationCounter > 1) && ($label == 'inspiration')) ){
                  continue;
                }
              ?>
                <li class="<?php echo ($mainImage->getPosition() == $_image->getPosition()) ? 'active' : '' ?>">
                    <a class="thumb-link <?php echo $label; ?>" href="#" title="<?php echo $this->escapeHtml($_image->getLabel()) ?>" data-image-index="<?php echo $i; ?>"><h4 class="to-uppercase"><?php echo $_image->getLabel(); ?></h4>
                        <img src="<?php echo $this->helper('validoc_board/image')->init($this->getBoard(), 'thumbnail', $_image->getFile()); ?>"
                              alt="<?php echo $this->escapeHtml($_image->getLabel()) ?>" class="<?php echo $i; ?>" />
                    </a>
                </li>
                <?php $i++; endforeach; ?>
                <?php
                    if(!empty($floorplans)): ?>
                    <h4 class="to-uppercase floorplans-title"><?php echo "floorplans"; ?></h4>
                    <ul class="rooms-floorplans">
                  <?php foreach($floorplans as $floorplan): ?>
                      <li>
                        <a class="floorplan" href="<?php echo Mage::getBaseUrl()."designer-floorplan/floorplan/view/id/".$floorplan["floorplan_id"]; ?>" title="<?php echo $floorplan["name"]; ?>">
                          <!-- <h4 class="to-uppercase"><?php //echo $floorplan["name"]; ?>
                          </h4> -->
                          <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$floorplan["image"]; ?>">
                        </a>
                      </li>
                    <?php endforeach; ?>
                    </ul>
                  <?php endif; ?>
        </ul>
        <ul class="inspiration-carousel" style="display: none;">
          <?php foreach($this->getGalleryImages() as $img): ?>
            <?php
              $label = $img->getLabel();
              $label = strtolower(trim($label));
            ?>
            <?php if($label == 'inspiration'): ?>
              <li><a href="#"><img src="<?php echo $this->helper('validoc_board/image')->init($this->getBoard(), 'thumbnail', $img->getFile()); ?>" alt="<?php echo $this->escapeHtml($img->getLabel()); ?>"></a></li>
            <?php endif; ?>
          <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>

<?php echo $this->getChildHtml('after'); ?>