<?php $posts = $this->getPosts(); ?>
<div id="messages_product_view">
    <?php Mage::app()->getLayout()->getMessagesBlock()->setMessages(Mage::getSingleton('customer/session')->getMessages(true)); ?>
    <?php echo Mage::app()->getLayout()->getMessagesBlock()->getGroupedHtml(); ?>
</div>

<div class="postWrapper">
    <ul class="blog-thumbnail">
        <?php foreach ($posts as $post): ?>
            <?php if ($post->getShowThumbnailInHome()) { ?>
                <li>
                    <a href="<?php echo $post->getAddress(); ?>">
                        <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $post->getThumbnail(); ?>" alt="<?php echo $post->getName(); ?>" />
                    </a>
                </li>
            <?php } ?>
        <?php endforeach; ?>
    </ul>
</div>
